-- Auto-generated by the Gen1Recomp content editor.  Edit in the editor
-- and save again to regenerate this file. Manual edits are overwritten.
return (function()
  local p = {}
  p.aiClasses = (function() return 
{}
  end)()
  p.audio = (function() return 
{}
  end)()
  p.badgeGates = (function() return 
{}
  end)()
  p.battle_anims = (function() return 
{}
  end)()
  p.boot = (function() return 
{}
  end)()
  p.constants = (function() return 
{}
  end)()
  p.deleted = (function() return 
{
  items = {},
  pokemon = {},
  trainers = {},
}
  end)()
  p.diploma = (function() return 
{}
  end)()
  p.eventFlags = (function() return 
{}
  end)()
  p.fishing = (function() return 
{}
  end)()
  p.flyWarps = (function() return 
{}
  end)()
  p.font = (function() return 
{}
  end)()
  p.game = (function() return 
"firered"
  end)()
  p.gbcWorld = (function() return 
{
  groupColors = {},
}
  end)()
  p.gen3 = (function() return 
{}
  end)()
  p.gen3Exact = (function() return 
{}
  end)()
  p.gen3Modes = (function() return 
{}
  end)()
  p.hiddenItems = (function() return 
{}
  end)()
  p.id = (function() return 
"my_content"
  end)()
  p.intro = (function() return 
{}
  end)()
  p.items = (function() return 
{}
  end)()
  p.layeredMaps = (function()
    local t = {}
    return t
  end)()
  p.ledges = (function() return 
{}
  end)()
  p.mapAssemblies = (function() return 
{}
  end)()
  p.mapBgAssign = (function() return 
{}
  end)()
  p.mapBgSets = (function() return 
{}
  end)()
  p.mapHooks = (function() return 
{}
  end)()
  p.mapStamps = (function() return 
{}
  end)()
  p.mapTileSources = (function()
    local t = {}
    return t
  end)()
  p.mapWarpNodes = (function()
    local t = {}
    return t
  end)()
  p.map_scripts = (function() return 
{}
  end)()
  p.maps = (function()
    local t = {}
    return t
  end)()
  p.marts = (function() return 
{}
  end)()
  p.menuGfx = (function() return 
{}
  end)()
  p.moveEffects = (function() return 
{}
  end)()
  p.movements = (function() return 
{}
  end)()
  p.moves = (function() return 
{}
  end)()
  p.name = (function() return 
"My Content"
  end)()
  p.namedBgSets = (function() return 
{}
  end)()
  p.nextMapIndex = (function() return 
1000
  end)()
  p.nextStamp = (function() return 
1
  end)()
  p.nextWarpNode = (function() return 
1
  end)()
  p.palettes = (function() return 
{}
  end)()
  p.playerPics = (function() return 
{}
  end)()
  p.playerSprites = (function() return 
{}
  end)()
  p.pokedex = (function() return 
{}
  end)()
  p.pokemon = (function() return 
{}
  end)()
  p.profile = (function() return 
"content"
  end)()
  p.runtimeTileAnims = (function() return 
{}
  end)()
  p.scriptSteps = (function() return 
{}
  end)()
  p.specialEncounters = (function() return 
{}
  end)()
  p.sprites = (function() return 
{}
  end)()
  p.starterRemap = (function() return 
{}
  end)()
  p.strings = (function() return 
{}
  end)()
  p.talkScripts = (function() return 
{}
  end)()
  p.text = (function() return 
{}
  end)()
  p.text_pointers = (function() return 
{}
  end)()
  p.theme = (function() return 
{}
  end)()
  p.tilesets = (function()
    local t = {}
    return t
  end)()
  p.title = (function() return 
{}
  end)()
  p.townMap = (function() return 
{}
  end)()
  p.trainerCard = (function() return 
{}
  end)()
  p.trainer_headers = (function() return 
{}
  end)()
  p.trainers = (function() return 
{}
  end)()
  p.type_foresight = (function() return 
{}
  end)()
  p.type_matchups = (function() return 
{}
  end)()
  p.types = (function() return 
{}
  end)()
  p.uiFitted = (function() return 
{}
  end)()
  p.uiMismatch = (function() return 
{}
  end)()
  p.uiScripts = (function() return 
{}
  end)()
  return p
end)()
