-- generated by tools/content-editor (Gen 3).
return function(mod)
  if mod.generation ~= 3 then return end
  local function assetPaths(value)
    if type(value) ~= "table" then return value end
    for key, child in pairs(value) do
      if type(child) == "string" and tostring(key):match("^sprite") and child:sub(1,7) == "assets/" then
        value[key] = mod.path .. "/" .. child
      elseif type(child) == "table" then assetPaths(child) end
    end
    return value
  end
end
