-- generated by tools/content-editor (Gen 3).
return function(mod)
  if mod.generation ~= 3 then return end
  do
    local events=mod.events
    local rawOn=events.on
    local ready={}
    events.on=function(self,name,callback,priority)
      if name=="game.ready" and type(callback)=="function" then
        ready[#ready+1]={callback=callback,priority=priority or 0,order=#ready}
      end
      return rawOn(self,name,callback,priority)
    end
    rawOn(events,"mods.loaded",function(payload)
      local data=type(payload)=="table" and payload.data
      if not (type(data)=="table" and data.game3Maps) then return end
      table.sort(ready,function(a,b)
        if a.priority~=b.priority then return a.priority>b.priority end
        return a.order<b.order
      end)
      local ctx={game={data=data},editor=true}
      for _,handler in ipairs(ready) do pcall(handler.callback,ctx) end
    end,-100)
  end
do
  local schema=require("src.mods.Schemas")
  local field=schema.REGISTRIES.pokemon.gen3Fields.index
  local expanded=schema.f.int(1,65535)
  -- Change the shared descriptor, including cached Gen 3 schema shapes.
  field.inner=expanded;field.desc=expanded.desc
end

local connections=(function()
-- A direction accepts a legacy connection or an ordered list of connections.
local M={directions={"north","south","east","west"}}
M.opposite={north="south",south="north",east="west",west="east"}
M.alias={up="north",down="south",left="west",right="east"}
local cache=setmetatable({},{__mode="k"})
local empty={}
local function cached(connections)
  if not connections then connections=empty end
  local result=cache[connections]
  if result then return result end
  result={rows={}};cache[connections]=result
  for _,dir in ipairs(M.directions) do
    local value=connections[dir];local rows={}
    if value then
      if type(value)~="table" then rows[1]={map=value,offset=0}
      elseif value.map or value.mapId then rows[1]=value
      else rows=value end
    else
      for _,c in ipairs(connections) do
        if (M.alias[c.dir] or c.dir)==dir then rows[#rows+1]=c end
      end
    end
    result[dir]=rows
    for i,c in ipairs(rows) do
      local row={dir,c,i};result.rows[#result.rows+1]=row
    end
  end
  return result
end
-- Cached arrays can be traversed with ipairs, including nested/early-exit loops.
function M.list(connections,dir) return cached(connections)[dir] or empty end
function M.each(connections) return cached(connections).rows end
function M.invalidate(connections) if connections then cache[connections]=nil end end
function M.put(connections,dir,rows)
  M.invalidate(connections)
  connections[dir]=#rows==0 and nil or #rows==1 and rows[1] or rows
end
function M.copy(value)
  if type(value)~="table" then return value end
  local out={};for k,v in pairs(value) do out[k]=M.copy(v) end;return out
end
-- New ROM caches use ordered {dir,map,offset} records. Authoring and export
-- use direction buckets, including a list when a side has several exits.
function M.normalize(connections)
  local out={}
  for _,dir in ipairs(M.directions) do
    local rows=M.copy(M.list(connections,dir))
    for _,c in ipairs(rows) do c.dir=nil end
    if #rows>0 then M.put(out,dir,rows) end
  end
  return out
end
function M.validate(connections)
  for dir,value in pairs(connections or {}) do
    assert(M.opposite[dir],"Unknown connection direction: "..tostring(dir))
    assert(type(value)=="table","Connection must contain a destination and offset")
    for _,c in ipairs(M.list(connections,dir)) do
      assert(type(c)=="table" and type(c.map or c.mapId)=="string","Choose a connection destination")
      local n=c.offset or 0;assert(type(n)=="number" and n==n and n%1==0,"Connection offset must be a whole number")
    end
  end
end
-- Repair the verified stock cache overwrite, never authored replacements.
-- Source: pret/pokefirered data/maps/SixIsland_WaterPath/map.json.
function M.recover(maps,skip)
  local id="FR_SIX_ISLAND_WATER_PATH";local map=maps[id]
  if not map or (skip or {})[id] then return end
  local old=M.list(map.connections,"west")
  if #old~=1 or old[1].map~="FR_SIX_ISLAND_RUIN_VALLEY" or old[1].offset~=80 then return end
  local rows={{map="FR_SIX_ISLAND_GREEN_PATH",offset=0},{map="FR_SIX_ISLAND",offset=40},{map="FR_SIX_ISLAND_RUIN_VALLEY",offset=80}}
  for _,c in ipairs(rows) do
    local dest=maps[c.map];local found=false
    for _,back in ipairs(M.list(dest and dest.connections,"east")) do if back.map==id and back.offset==-c.offset then found=true end end
    if not found then return end
  end
  M.put(map.connections,"west",rows)
end
function M.landing(def,conn,dir,x,y)
  dir=M.alias[dir] or dir
  local l=def and def.midLayout or def or {};local w,h=l.width or 0,l.height or 0
  local off=conn.offset or 0
  if dir=="west" then x,y=w-1,y-off
  elseif dir=="east" then x,y=0,y-off
  elseif dir=="north" then x,y=x-off,h-1
  elseif dir=="south" then x,y=x-off,0 else return end
  if x>=0 and y>=0 and x<w and y<h then return x,y end
end
return M

end)()
local connectionRuntime=(function()
local M={}
function M.install(mod,C,authored)
  local Runtime=require("src.mods.Runtime")
  local Map=require("src.core.game3.map")
  local Collision=require("src.core.game3.collision")
  local function bridge(object,name,fn)
    local key="editor.gen3.connections."..name
    if not object[key] then object[key]=true;local original=object[name];object[name]=function(...) return Runtime.call(key,original,...) end end
    mod.hooks:wrap(key,fn)
  end
  mod.events:on("game.ready",function(ev) C.recover(ev.game.data.maps,authored) end)
  local function size(def) local l=def.midLayout or def;return l.width or 0,l.height or 0 end
  local function delta(dir,offset,from,to)
    local w,h=size(from);local dw,dh=size(to)
    if dir=="north" then return offset,-dh elseif dir=="south" then return offset,h
    elseif dir=="west" then return -dw,offset else return w,offset end
  end
  bridge(Map,"loadNeighborsDepth1",function(_,game,def)
    local result,list={},{};local maps=game and game.data and game.data.maps or {}
    for _,row in ipairs(C.each(def and def.connections)) do
      local dir,c,i=row[1],row[2],row[3]
      local id=c.map or c.mapId;local dest=maps[id]
      if dest then
        Map.ensureMidLayout(game,id,dest)
        local ox,oy=delta(dir,c.offset or 0,def,dest)
        local n={dir=dir,map=id,mapId=id,def=dest,offset=c.offset or 0,ox=ox,oy=oy}
        result[i==1 and dir or dir..":"..i]=n;list[#list+1]=n
        Map._loadedLayouts[id]=true
      end
    end
    Map.neighbors=result;Map.neighborList=list;return result
  end)
  bridge(Map,"overscanSlices",function()
    local rows={};for key,n in pairs(Map.neighbors or {}) do rows[#rows+1]={dir=n.dir or key,mapId=n.map,offset=n.offset} end;return rows
  end)
  bridge(Map,"computeWorld",function(_,maps,rootId,hops,reachW,reachH,ensure)
    local root=maps and maps[rootId];if not root then return {} end
    ensure=ensure or function() end;ensure(rootId,root)
    local rw,rh=size(root);local out,seen,queue={},{[rootId]=true},{{def=root,ox=0,oy=0,hops=0}};local index=1
    while queue[index] do
      local current=queue[index];index=index+1
      for _,row in ipairs(C.each(current.def.connections)) do
        local dir,c=row[1],row[2]
        local id=c.map or c.mapId;local dest=maps[id]
        if dest and not seen[id] then
          ensure(id,dest);local dx,dy=delta(dir,c.offset or 0,current.def,dest)
          local ox,oy=current.ox+dx,current.oy+dy;local w,h=size(dest)
          local inReach=reachW and reachH and ox+w>-reachW and ox<rw+reachW and oy+h>-reachH and oy<rh+reachH
          if current.hops+1<=(hops or 0) or inReach then
            seen[id]=true;out[#out+1]={id=id,def=dest,ox=ox,oy=oy}
            if current.hops+1<(hops or 0) or inReach then queue[#queue+1]={def=dest,ox=ox,oy=oy,hops=current.hops+1} end
          end
        end
      end
    end
    return out
  end)
  -- Cell sampling must not enter Runtime.call or allocate iterator closures.
  Map.worldMidAt=function(x,y,def)
    local l=def and def.midLayout
    if not l then return 0,nil end
    local pair=l.pair or def.pair
    if x>=0 and y>=0 and x<l.width and y<l.height then return l:midAt(x,y),pair end
    for _,n in ipairs(Map.neighborList or {}) do
      local nl=n.def.midLayout;local nx,ny=x-n.ox,y-n.oy
      if nl and nx>=0 and ny>=0 and nx<nl.width and ny<nl.height then
        return nl:midAt(nx,ny),nl.pair or n.def.pair or pair
      end
    end
    for _,n in ipairs(Map.world or {}) do
      local nl=n.def~=def and n.def and n.def.midLayout
      local nx,ny=x-n.ox,y-n.oy
      if nl and nx>=0 and ny>=0 and nx<nl.width and ny<nl.height then
        return nl:midAt(nx,ny),nl.pair or n.def.pair or pair
      end
    end
    return l:midAt(x,y),pair,true
  end
  bridge(Collision,"connectionLanding",function(_,def,c,dir,x,y) return C.landing(def,c,dir,x,y) end)
  bridge(require("src.core.game3.itemfinder"),"scan",function(proceed,opts)
    if not opts.neighbors or not opts.eventsFor or not opts.width or not opts.height then return proceed(opts) end
    local scan={};for k,v in pairs(opts) do scan[k]=v end;scan.events={};scan.neighbors=nil
    for _,ev in ipairs(opts.events or {}) do scan.events[#scan.events+1]=ev end
    local current={width=opts.width,height=opts.height}
    for key,n in pairs(opts.neighbors) do
      local dir=n.dir or C.alias[key] or key
      if C.opposite[dir] and n.def then
        local ox,oy=delta(dir,n.offset or 0,current,n.def)
        for _,ev in ipairs(opts.eventsFor(n.map or n.mapId) or {}) do
          if not ev.underfoot and (ev.type=="hidden_item" or ev.kind==7) and ev.x and ev.y then
            local x,y=ev.x+ox,ev.y+oy
            if x<0 or y<0 or x>=opts.width or y>=opts.height then
              local copy=C.copy(ev);copy.x=x;copy.y=y;scan.events[#scan.events+1]=copy
            end
          end
        end
      end
    end
    return proceed(scan)
  end)
  bridge(Collision,"tryConnection",function(proceed,game,x,y,dir,run)
    local def=Collision._mapDef;local cardinal=C.alias[dir] or dir
    if not def then return false end
    local selected
    for _,c in ipairs(C.list(def.connections,cardinal)) do
      local id=c.map or c.mapId;local dest=game and game.data and game.data.maps[id]
      if dest then Map.ensureMidLayout(game,id,dest);if C.landing(dest,c,dir,x,y) then selected=c;break end end
    end
    if not selected then return false end
    -- Delegate collision, surfing, events and the actual transition to native code.
    local proxy={};for k,v in pairs(def) do proxy[k]=v end
    proxy.connections={[dir]=selected,[cardinal]=selected};Collision._mapDef=proxy
    local ok,result=pcall(proceed,game,x,y,dir,run)
    if Collision._mapDef==proxy then Collision._mapDef=def end
    if not ok then error(result,0) end;return result
  end)
end
return M

end)()
connectionRuntime.install(mod,connections,{})
  local function assetPaths(value)
    if type(value) ~= "table" then return value end
    for key, child in pairs(value) do
      if type(child) == "string" and tostring(key):match("^sprite") and child:sub(1,7) == "assets/" then
        value[key] = mod.path .. "/" .. child
      elseif type(child) == "table" then assetPaths(child) end
    end
    return value
  end
  local clockCfg={
  day = 10,
  morning = 4,
  night = 18,
}
  local clockRead=function(t, cfg, DAYS, MONTHS)
  local hour, minute = t.hour, t.min
  if cfg.testHour then hour, minute = cfg.testHour, 0 end
  local part = 1
  if hour >= cfg.night or hour < cfg.morning then part = 2 elseif hour < cfg.day then part = 0 end
  local h12 = hour % 12
  if h12 == 0 then h12 = 12 end
  return {
    strings = { DAYS[t.wday], tostring(t.day) .. " " .. MONTHS[t.month],
      ("%d:%02d %s"):format(h12, minute, hour < 12 and "AM" or "PM") },
    day = t.wday - 1, hour = hour, minute = minute, part = part,
  }
end
  local clockDays={
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
}
  local clockMonths={
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
}
  -- Real time clock: special 57600 "Read the clock" (Gen3Clock.lua).
  mod.events:on("game.ready",function()
    local okN,Natives=pcall(require,"src.core.game3.scripting.natives")
    if not okN or type(Natives)~="table" or type(Natives.ALLOW)~="table" then return end
    Natives.ALLOW["special:57600"]=function(ctx,adapters)
      local c=clockRead(os.date("*t"),clockCfg,clockDays,clockMonths)
      for i,s in ipairs(c.strings) do
        if ctx and ctx.stringVars then ctx.stringVars[i]=s end
        if adapters and adapters.setStringVar then pcall(adapters.setStringVar,i,s) end
      end
      -- 0x8004-0x8007 are the script's own (special) variables
      local okV,Flags=pcall(require,"src.core.game3.scripting.flags")
      if okV and Flags.setVar then
        Flags.setVar(nil,ctx,32772,c.day)
        Flags.setVar(nil,ctx,32773,c.hour)
        Flags.setVar(nil,ctx,32774,c.minute)
        Flags.setVar(nil,ctx,32775,c.part)
      end
      return false
    end
  end)

local contestEvo=(function()
local M={}
-- Emerald's Beauty evolution reads mon.beauty, but Pokeblocks raise mon.contest.beauty.
function M.install(mod,rows)
  local Pokemon=require("src.core.game3.pokemon")
  local EVO_BEAUTY=require("src.core.game3.evolution").EVO_BEAUTY
  local conditions
  local function lookup()
    if conditions then return conditions end
    conditions={}
    for _,row in ipairs(rows) do
      local from,into=mod.content.pokemon:get(row.from),mod.content.pokemon:get(row.into)
      if from and into then conditions[from.index.."|"..into.index.."|"..row.param]=row.condition end
    end
    return conditions
  end
  mod.hooks:wrap("evolution.check",function(proceed,game,mon,view,ctx)
    if view.methodId~=EVO_BEAUTY then return proceed(game,mon,view,ctx) end
    local from=tonumber(Pokemon.speciesOf(mon) or mon.species) or 0
    local condition=lookup()[from.."|"..view.speciesId.."|"..view.param] or "beauty"
    local value=tonumber(mon.contest and mon.contest[condition]) or 0
    if condition=="beauty" then value=math.max(value,tonumber(mon.beauty) or 0) end
    return view.param<=value
  end)
end
return M

end)()
contestEvo.install(mod,{})
end
