-- Remaining native operands, named individually rather than numbered settings.
-- Positional layouts follow the linked FireRed opcode table and importer.
return function(schema)
  schema("compare_local_to_local copylocal",{{false,"First temporary slot"},{false,"Second temporary slot"}})
  schema("compare_local_to_value",{{false,"Temporary slot to check"},{false,"Number to compare"}})
  schema("compare_local_to_ptr",{{false,"Temporary slot to check"},{false,"Memory address to compare"}})
  schema("compare_ptr_to_local",{{false,"Memory address to check"},{false,"Temporary slot to compare"}})
  schema("compare_ptr_to_value",{{false,"Memory address to check"},{false,"Number to compare"}})
  schema("compare_ptr_to_ptr",{{false,"First memory address"},{false,"Second memory address"}})
  schema("copybyte",{{false,"Destination memory address"},{false,"Source memory address"}})
  schema("setptr",{{false,"Memory address"}})
  schema("loadbytefromptr setptrbyte",{{false,"Temporary slot"}})
  schema("callnative gotonative",{{"fn","Built-in function address"}})
  schema("gotostd_if callstd_if",{{false,"Continue when the previous check","condition"},{false,"Common game action","common"}})
  schema("setmysteryeventstatus",{{false,"Mystery Event result"}})
  schema("initclock",{{false,"Hour"},{false,"Minute"}})
  schema("applymovement",{{"localId","Character","character"},{"movement","Movement route"}})
  schema("applymovementat",{{"localId","Character number on destination map"},{"movement","Movement route"},{false,"Destination map group"},{false,"Destination map number"}})
  schema("waitmovementat",{{"localId","Character number on destination map"},{false,"Destination map group"},{false,"Destination map number"}})
  schema("removeobjectat addobjectat showobjectat hideobjectat",{{"localId","Character number on destination map"},{false,"Destination map group"},{false,"Destination map number"}})
  schema("setobjectmovementtype",{{"localId","Character","character"},{false,"Idle movement","idleMovement"}})
  schema("message messageautoscroll braillemessage loadhelp getbraillestringwidth",{{"ptr","Message","dialogue"}})
  schema("drawbox erasebox drawboxtext",{{false,"Left edge"},{false,"Top edge"},{false,"Right edge"},{false,"Bottom edge"}})
  schema("showcontestpainting",{{false,"Contest painting number"}})
  schema("bufferleadmonspeciesname",{{"dest","Text slot to fill"}})
  schema("bufferdecorationname",{{"dest","Text slot to fill"},{"src","Decoration number"}})
  schema("bufferstdstring",{{"dest","Text slot to fill"},{"src","Common phrase number"}})
  schema("bufferstring",{{"dest","Text slot to fill"},{"src","Text to insert","dialogue"}})
  schema("bufferboxname",{{"dest","Text slot to fill"},{"src","Storage box (0 = first)"}})
  schema("bufferitemnameplural",{{"dest","Text slot to fill"},{"src","Item","item"},{false,"Quantity"}})
  schema("pokemart",{{"ptr","Shop inventory","shop"}})
  schema("pokemartdecoration pokemartdecoration2",{{"ptr","Decoration inventory address"}})
  schema("playslotmachine",{{false,"Slot machine number"}})
  schema("setberrytree",{{false,"Berry tree number"},{false,"Berry type number"},{false,"Growth stage"}})
  schema("getpokenewsactive",{{false,"Save the news result in"}})
  schema("dofieldeffect waitfieldeffect",{{false,"Map effect number"}})
  schema("setfieldeffectargument",{{false,"Map effect setting number"},{false,"Setting value"}})
  schema("setrespawn",{{false,"Healing location number"}})
  schema("setstepcallback",{{false,"Behavior after each player step"}})
  schema("setmaplayoutindex",{{false,"Map layout number"}})
  schema("setobjectsubpriority",{{false,"Character number"},{false,"Map group"},{false,"Map number"},{false,"Drawing order"}})
  schema("resetobjectsubpriority",{{false,"Character number"},{false,"Map group"},{false,"Map number"}})
  schema("createvobject",{{false,"Character appearance number"},{false,"Temporary character number"},{false,"Map column"},{false,"Map row"},{false,"Height above ground"},{false,"Facing direction","direction"}})
  schema("turnvobject",{{false,"Temporary character number"},{false,"Facing direction","direction"}})
  schema("addelevmenuitem",{{false,"Menu position"},{false,"Floor number"},{false,"Destination map group"},{false,"Destination map number"}})
  schema("checkcoins",{{false,"Save the coin count in"}})
  schema("setvaddress",{{false,"Starting address of the relocated event"}})
  schema("vgoto vcall",{{false,"Destination event address"}})
  schema("vgoto_if vcall_if",{{false,"Continue when the previous check","condition"},{false,"Destination event address"}})
  schema("vmessage vbuffermessage",{{false,"Message address in the relocated event"}})
  schema("vbufferstring",{{false,"Text slot to fill"},{false,"Text address in the relocated event"}})
  schema("incrementgamestat",{{false,"Game statistic number"}})
  schema("textcolor",{{"color","Text color number"}})
  schema("comparestat",{{false,"Game statistic number"},{false,"Number to compare"}})
  schema("setmonmodernfatefulencounter checkmonmodernfatefulencounter",{{false,"Pokémon on the team","teamSlot"}})
  schema("setmonmetlocation",{{false,"Pokémon on the team","teamSlot"},{false,"Meeting location number"}})
  schema("setworldmapflag",{{"flag","Saved switch for the visited location"}})
  schema("adddecoration removedecoration checkdecor checkdecorspace",{{false,"Decoration number"}})
  schema("trainerbattle",{{"trainer","Trainer","trainer"},{"type","Battle format"}})
end
