-- Load the open mod using the real runtime loader and an isolated, read-only
-- filesystem view. Never change the player's enable flags or load other mods.
local M = {}

function M.load(data, path, opts)
  local ModIO = require("ModIO")
  local Json = require("src.link.Json")
  local manifest = assert(Json.decode(assert(ModIO.readText(path .. "/manifest.json"))))
  local id = assert(manifest.id)
  local prefix = "mods/" .. id
  local function disk(rel)
    if rel == prefix then return path end
    if rel:sub(1, #prefix + 1) == prefix .. "/" then
      local tail = rel:sub(#prefix + 2)
      for part in tail:gmatch("[^/\\]+") do if part == ".." then return nil end end
      return path .. "/" .. tail
    end
  end
  local fs, memory = {}, {}
  function fs.read(rel)
    if memory[rel] then return memory[rel] end
    local full = disk(rel)
    if full then
      local body=ModIO.readText(full)
      if opts and opts.baseOnly and body and body:sub(1,55):find("generated by tools/content-editor",1,true) then return "return function() end" end
      return body
    end
    if rel:match("^data/") or rel:match("^firered/") or rel:match("^assets/") then
      return love and love.filesystem and love.filesystem.read(rel)
    end
  end
  function fs.write(rel,bytes) memory[rel]=bytes;return true end -- isolated loader migration state
  function fs.load(rel)
    local bytes, err = fs.read(rel)
    if not bytes then return nil, err end
    return loadstring(bytes, "@" .. rel)
  end
  function fs.getDirectoryItems(rel)
    if rel == "mods" then return { id } end
    local full = disk(rel)
    return full and ModIO.directoryNames(full) or {}
  end
  function fs.getInfo(rel, kind)
    if memory[rel] then return (not kind or kind=="file") and {type="file",size=#memory[rel]} or nil end
    local info
    if rel == "mods" or rel == prefix then info = {type="directory"}
    else
      local full = disk(rel)
      local bytes = full and ModIO.readText(full)
      if bytes then info = {type="file",size=#bytes}
      elseif full and #ModIO.directoryNames(full) > 0 then info = {type="directory"} end
    end
    if info and (not kind or kind == info.type) then return info end
  end
  local loader = require("src.mods.Loader").new({fs=fs,generation=3})
  function loader:_loadState()
    self.disabled, self.gen2Forced, self.modOptions = {}, {}, {}
    self.safeMode = false
  end
  loader:load(data)
  local status = loader:status()
  for _, mod in ipairs(status.loaded or {}) do
    if mod.id == id then
      data._editorGen3Catalog = {}
      for _, name in ipairs(require("Gen3").registries) do
        local records = {}
        for key, value in loader.content[name]:each() do records[tostring(key)] = value end
        data._editorGen3Catalog[name] = records
      end
      return loader
    end
  end
  local errors = {}
  for _, value in ipairs(status.errors or {}) do errors[#errors+1] = tostring(value) end
  local mod = loader.mods[id]
  return nil, table.concat(errors, "; ") .. " " .. tostring(mod and (mod.failure or mod.skipReason) or "Mod did not load")
end

return M
