-- Load the open mod using the real runtime loader and an isolated, read-only
-- filesystem view. Never change the player's enable flags or load other mods.
local M = {}

function M.load(data, path, opts)
  local ModIO = require("ModIO")
  local Json = require("src.link.Json")
  local manifest = assert(Json.decode(assert(ModIO.readText(path .. "/manifest.json"))))
  local id = assert(manifest.id)
  local report = {id=id, counts={}, messages={}, rejected={},addedRecords={pokemon={},moves={}}}
  data._editorGen3Report=report
  data._editorGen3Catalog=nil
  data._gen3EditorContent=nil
  local baseIds={}
  for _,name in ipairs({"pokemon","moves"}) do
    baseIds[name]={}
    for key in pairs(require("Gen3").catalog(data,name)) do baseIds[name][key]=true end
  end
  local prefix = "mods/" .. id
  local function disk(rel)
    if rel == prefix then return path end
    if rel:sub(1, #prefix + 1) == prefix .. "/" then
      local tail = rel:sub(#prefix + 2)
      for part in tail:gmatch("[^/\\]+") do if part == ".." then return nil end end
      return path .. "/" .. tail
    end
  end
  local fs, memory = {}, {}
  function fs.read(rel)
    if memory[rel] then return memory[rel] end
    local full = disk(rel)
    if full then
      local body=ModIO.readText(full)
      if opts and opts.baseOnly and (rel==prefix.."/main.lua" or rel==prefix.."/editor_apply.lua")
          and body and body:sub(1,55):find("generated by tools/content-editor",1,true) then return "return function() end" end
      return body
    end
    if rel:match("^data/") or rel:match("^firered/") or rel:match("^leafgreen/") or rel:match("^assets/") then
      return love and love.filesystem and love.filesystem.read(rel)
    end
  end
  function fs.write(rel,bytes) memory[rel]=bytes;return true end -- isolated loader migration state
  function fs.load(rel)
    local bytes, err = fs.read(rel)
    if not bytes then return nil, err end
    return loadstring(bytes, "@" .. rel)
  end
  function fs.getDirectoryItems(rel)
    if rel == "mods" then return { id } end
    local full = disk(rel)
    return full and ModIO.directoryNames(full) or {}
  end
  function fs.getInfo(rel, kind)
    if memory[rel] then return (not kind or kind=="file") and {type="file",size=#memory[rel]} or nil end
    local info
    if rel == "mods" or rel == prefix then info = {type="directory"}
    else
      local full = disk(rel)
      local bytes = full and ModIO.readText(full)
      if bytes then info = {type="file",size=#bytes}
      elseif full and #ModIO.directoryNames(full) > 0 then info = {type="directory"} end
    end
    if info and (not kind or kind == info.type) then return info end
  end
  local loader = require("src.mods.Loader").new({fs=fs,generation=3})
  -- Mods frequently catch registration failures themselves. Keep those
  -- diagnostics, even when the runtime considers the entry point loaded.
  local makeApi=loader._api
  function loader:_api(mod)
    local api=makeApi(self,mod)
    for _,level in ipairs({"warn","error"}) do
      local original=api.log[level]
      api.log[level]=function(log,fmt,...)
        local ok,message=pcall(string.format,tostring(fmt),...)
        report.messages[#report.messages+1]=ok and message or tostring(fmt)
        return original(log,fmt,...)
      end
    end
    for _,name in ipairs({"pokemon","moves"}) do
      local registry=api.content[name]
      for _,operation in ipairs({"register","patch","override"}) do
        local original=registry[operation]
        registry[operation]=function(self,key,value,...)
          local ok,result=pcall(original,self,key,value,...)
          if not ok then
            report.rejected[#report.rejected+1]={registry=name,id=key,operation=operation,error=tostring(result)}
            error(result,0)
          end
          return result
        end
      end
    end
    return api
  end
  function loader:_loadState()
    self.disabled, self.gen2Forced, self.modOptions = {}, {}, {}
    self.safeMode = false
  end
  loader:load(data)
  local status = loader:status()
  for _,message in ipairs(status.errors or {}) do report.messages[#report.messages+1]=tostring(message) end
  for _, mod in ipairs(status.loaded or {}) do
    if mod.id == id then
      data._editorGen3Catalog = {}
      for _, name in ipairs(require("Gen3").registries) do
        local records = {}
        local total,added=0,0
        for key, value in loader.content[name]:each() do
          records[tostring(key)] = require("src.mods.Merge").deepCopy(value)
          total=total+1
          if baseIds[name] and not baseIds[name][tostring(key)] then
            added=added+1;report.addedRecords[name][tostring(key)]=true
          end
        end
        report.counts[name]={total=total,added=added}
        data._editorGen3Catalog[name] = records
      end
      report.loaded=true
      data._editorEvolutionReference={}
      local exports=loader.exports and loader.exports[id]
      if exports and type(exports.evolutionsOf)=="function" then
        for species in pairs(data._editorGen3Catalog.pokemon or {}) do
          local ok,value=pcall(exports.evolutionsOf,species)
          if ok and type(value)=="table" then data._editorEvolutionReference[species]=value end
        end
      end
      return loader
    end
  end
  local errors = {}
  for _, value in ipairs(status.errors or {}) do errors[#errors+1] = tostring(value) end
  local mod = loader.mods[id]
  return nil, table.concat(errors, "; ") .. " " .. tostring(mod and (mod.failure or mod.skipReason) or "Mod did not load")
end

return M
