-- generated by tools/content-editor (Gen 3).
return function(mod)
  if mod.generation ~= 3 then return end
  local function assetPaths(value)
    if type(value) ~= "table" then return value end
    for key, child in pairs(value) do
      if type(child) == "string" and tostring(key):match("^sprite") and child:sub(1,7) == "assets/" then
        value[key] = mod.path .. "/" .. child
      elseif type(child) == "table" then assetPaths(child) end
    end
    return value
  end
  mod.content.text:override("EditorQuest_event_builder_test_QUEST_1_Text_done", assetPaths({
  {
      s = "Enjoy!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("EditorQuest_event_builder_test_QUEST_1_Text_full", assetPaths({
  {
      s = "Make room in your Bag and come back.",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("EditorQuest_event_builder_test_QUEST_1_Text_missing", assetPaths({
  {
      s = "You have not met the requirement yet.",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("EditorQuest_event_builder_test_QUEST_1_Text_offer", assetPaths({
  {
      s = "Welcome, ",
      t = "text",
    },
  {
      t = "player",
    },
  {
      s = "!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("EditorQuest_event_builder_test_QUEST_1_Text_success", assetPaths({
  {
      s = "Here you go!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("EditorTalk_event_builder_test_1_Text", assetPaths({
  {
      s = "Welcome, ",
      t = "text",
    },
  {
      t = "player",
    },
  {
      s = "!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_BootedUpPC", assetPaths({
  {
      t = "player",
    },
  {
      s = " booted up the PC.",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_FoundOneItem", assetPaths({
  {
      t = "player",
    },
  {
      s = " found one ",
      t = "text",
    },
  {
      n = 2,
      t = "strvar",
    },
  {
      s = "!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_FoundTMHMContainsMove", assetPaths({
  {
      t = "player",
    },
  {
      s = " found",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      n = 2,
      t = "strvar",
    },
  {
      s = "!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_ObtainedTheX", assetPaths({
  {
      t = "player",
    },
  {
      s = " obtained",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "the ",
      t = "text",
    },
  {
      n = 2,
      t = "strvar",
    },
  {
      s = "!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_PutItemAway", assetPaths({
  {
      t = "player",
    },
  {
      s = " put away the",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      n = 2,
      t = "strvar",
    },
  {
      s = " in the ",
      t = "text",
    },
  {
      n = 3,
      t = "strvar",
    },
  {
      s = ".",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_RestoredPkmnToFullHealth", assetPaths({
  {
      s = "Thank you for waiting.",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "We've restored your POKéMON to",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "full health.",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_TakeYourPkmnForFewSeconds", assetPaths({
  {
      s = "OK. I'll take your POKéMON for a",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "few seconds.",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_TooBadBagFull", assetPaths({
  {
      s = "Too bad!",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "The BAG is full…",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_UsualPCServicesUnavailable", assetPaths({
  {
      s = "The usual PC services aren't",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "available right now…",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_WeHopeToSeeYouAgain", assetPaths({
  {
      s = "We hope to see you again!",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.text:override("Text_WelcomeWantToHealPkmn", assetPaths({
  {
      s = "Welcome to our POKéMON CENTER!",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "Would you like me to rest your",
      t = "text",
    },
  {
      t = "nl",
    },
  {
      s = "POKéMON to good health?",
      t = "text",
    },
  {
      t = "eos",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1", assetPaths({
  {
      op = "lock",
    },
  {
      op = "faceplayer",
    },
  {
      flag = 2305,
      op = "checkflag",
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EditorQuest_event_builder_test_QUEST_1_done",
    },
  {
      op = "message",
      ptr = "EditorQuest_event_builder_test_QUEST_1_Text_offer",
    },
  {
      op = "waitmessage",
    },
  {
      op = "yesnobox",
      x = 20,
      y = 8,
    },
  {
      op = "compare_var_to_value",
      value = 1,
      var = 32781,
    },
  {
      cond = 5,
      op = "goto_if",
      target = "EditorQuest_event_builder_test_QUEST_1_cancel",
    },
  {
      op = "closemessage",
    },
  {
      item = 13,
      op = "additem",
      quantity = 2,
    },
  {
      op = "compare_var_to_value",
      value = 1,
      var = 32781,
    },
  {
      cond = 5,
      op = "goto_if",
      target = "EditorQuest_event_builder_test_QUEST_1_full",
    },
  {
      flag = 2305,
      op = "setflag",
    },
  {
      op = "goto",
      target = "EditorQuest_event_builder_test_QUEST_1_success",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1_cancel", assetPaths({
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1_done", assetPaths({
  {
      op = "message",
      ptr = "EditorQuest_event_builder_test_QUEST_1_Text_done",
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1_full", assetPaths({
  {
      op = "message",
      ptr = "EditorQuest_event_builder_test_QUEST_1_Text_full",
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1_missing", assetPaths({
  {
      op = "message",
      ptr = "EditorQuest_event_builder_test_QUEST_1_Text_missing",
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:register("EditorQuest_event_builder_test_QUEST_1_success", assetPaths({
  {
      op = "message",
      ptr = "EditorQuest_event_builder_test_QUEST_1_Text_success",
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:register("EditorTalk_event_builder_test_1", assetPaths({
  {
      op = "lock",
    },
  {
      op = "faceplayer",
    },
  {
      op = "message",
      ptr = "EditorTalk_event_builder_test_1_Text",
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "closemessage",
    },
  {
      op = "release",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferBerryPouch", assetPaths({
  {
      dest = 2,
      op = "bufferstdstring",
      src = 28,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferItemsPocket", assetPaths({
  {
      dest = 2,
      op = "bufferstdstring",
      src = 24,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferKeyItemsPocket", assetPaths({
  {
      dest = 2,
      op = "bufferstdstring",
      src = 25,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferPocketName", assetPaths({
  {
      op = "compare_var_to_value",
      value = 1,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_BufferItemsPocket",
    },
  {
      op = "compare_var_to_value",
      value = 2,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_BufferKeyItemsPocket",
    },
  {
      op = "compare_var_to_value",
      value = 3,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_BufferPokeBallsPocket",
    },
  {
      op = "compare_var_to_value",
      value = 4,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_BufferTMCase",
    },
  {
      op = "compare_var_to_value",
      value = 5,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_BufferBerryPouch",
    },
  {
      dest = 2,
      op = "bufferstdstring",
      src = 24,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferPokeBallsPocket", assetPaths({
  {
      dest = 2,
      op = "bufferstdstring",
      src = 26,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_BufferTMCase", assetPaths({
  {
      dest = 2,
      op = "bufferstdstring",
      src = 27,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_ObtainItemMessage", assetPaths({
  {
      dest = 1,
      op = "bufferitemname",
      src = 32768,
    },
  {
      [1] = 32768,
      op = "checkitemtype",
    },
  {
      op = "call",
      target = "EventScript_BufferPocketName",
    },
  {
      op = "compare_var_to_value",
      value = 1,
      var = 32775,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_ObtainedItem",
    },
  {
      op = "setvar",
      value = 0,
      var = 32781,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_ObtainedItem", assetPaths({
  {
      [1] = 257,
      op = "playfanfare",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_ObtainedTheX",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitfanfare",
    },
  {
      op = "waitmessage",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_PutItemAway",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "setvar",
      value = 1,
      var = 32781,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_PC", assetPaths({
  {
      op = "lockall",
    },
  {
      id = 214,
      op = "special",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_BootedUpPC",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      id = 262,
      op = "special",
    },
  {
      op = "waitstate",
    },
  {
      id = 215,
      op = "special",
    },
  {
      op = "releaseall",
    },
  {
      op = "end",
    },
}))
  mod.content.map_scripts:override("EventScript_PickUpItem", assetPaths({
  {
      [1] = 32783,
      op = "removeobject",
    },
  {
      [1] = 32768,
      [2] = 32769,
      op = "additem",
    },
  {
      [1] = 257,
      op = "playfanfare",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_FoundOneItem",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitfanfare",
    },
  {
      op = "waitmessage",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_PutItemAway",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "setvar",
      value = 1,
      var = 32781,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_PkmnCenterNurse", assetPaths({
  {
      dest = 0,
      op = "loadword",
      value = "Text_WelcomeWantToHealPkmn",
    },
  {
      op = "callstd",
      std = 5,
    },
  {
      op = "compare_var_to_value",
      value = 0,
      var = 32781,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_PkmnCenterNurse_Goodbye",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_TakeYourPkmnForFewSeconds",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "call",
      target = "EventScript_PkmnCenterNurse_TakeAndHealPkmn",
    },
  {
      op = "goto",
      target = "EventScript_PkmnCenterNurse_ReturnPkmn",
    },
}))
  mod.content.map_scripts:override("EventScript_PkmnCenterNurse_Goodbye", assetPaths({
  {
      dest = 0,
      op = "loadword",
      value = "Text_WeHopeToSeeYouAgain",
    },
  {
      op = "callstd",
      std = 4,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_PkmnCenterNurse_ReturnPkmn", assetPaths({
  {
      dest = 0,
      op = "loadword",
      value = "Text_RestoredPkmnToFullHealth",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      localId = 32783,
      movement = { 91, 26, 254 },
      op = "applymovement",
    },
  {
      localId = 32783,
      op = "waitmovement",
    },
  {
      op = "goto",
      target = "EventScript_PkmnCenterNurse_Goodbye",
    },
}))
  mod.content.map_scripts:override("EventScript_PkmnCenterNurse_TakeAndHealPkmn", assetPaths({
  {
      localId = 32783,
      movement = { 47, 254 },
      op = "applymovement",
    },
  {
      localId = 32783,
      op = "waitmovement",
    },
  {
      [1] = 25,
      op = "dofieldeffect",
    },
  {
      [1] = 25,
      op = "waitfieldeffect",
    },
  {
      localId = 32783,
      movement = { 45, 254 },
      op = "applymovement",
    },
  {
      localId = 32783,
      op = "waitmovement",
    },
  {
      id = 0,
      op = "special",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_ReceivedItemFanfareDefault", assetPaths({
  {
      [1] = 32770,
      op = "playfanfare",
    },
  {
      op = "goto",
      target = "EventScript_ReceivedItemShowMsg",
    },
}))
  mod.content.map_scripts:override("EventScript_ReceivedItemFanfareItem", assetPaths({
  {
      [1] = 258,
      op = "playfanfare",
    },
  {
      op = "goto",
      target = "EventScript_ReceivedItemShowMsg",
    },
}))
  mod.content.map_scripts:override("EventScript_ReceivedItemFanfareKeyItem", assetPaths({
  {
      [1] = 318,
      op = "playfanfare",
    },
  {
      op = "goto",
      target = "EventScript_ReceivedItemShowMsg",
    },
}))
  mod.content.map_scripts:override("EventScript_ReceivedItemFanfareLevelUp", assetPaths({
  {
      [1] = 257,
      op = "playfanfare",
    },
  {
      op = "goto",
      target = "EventScript_ReceivedItemShowMsg",
    },
}))
  mod.content.map_scripts:override("EventScript_ReceivedItemShowMsg", assetPaths({
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitfanfare",
    },
  {
      op = "waitmessage",
    },
  {
      op = "callstd",
      std = 8,
    },
  {
      op = "call",
      target = "EventScript_RestorePrevTextColor",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("EventScript_RestorePrevTextColor", assetPaths({
  {
      [1] = 32786,
      [2] = 32787,
      op = "copyvar",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("std:0", assetPaths({
  {
      [1] = 32787,
      [2] = 32786,
      op = "copyvar",
    },
  {
      [1] = 3,
      color = 3,
      op = "textcolor",
    },
  {
      [1] = 32768,
      [2] = 32769,
      op = "additem",
    },
  {
      [1] = 32775,
      [2] = 32781,
      op = "copyvar",
    },
  {
      op = "call",
      target = "EventScript_ObtainItemMessage",
    },
  {
      [1] = 32786,
      [2] = 32787,
      op = "copyvar",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("std:1", assetPaths({
  {
      [1] = 32768,
      [2] = 32769,
      op = "checkitemspace",
    },
  {
      [1] = 32775,
      [2] = 32781,
      op = "copyvar",
    },
  {
      dest = 1,
      op = "bufferitemname",
      src = 32768,
    },
  {
      [1] = 32768,
      op = "checkitemtype",
    },
  {
      op = "call",
      target = "EventScript_BufferPocketName",
    },
  {
      op = "compare_var_to_value",
      value = 1,
      var = 32775,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_PickUpItem",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_TooBadBagFull",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "setvar",
      value = 0,
      var = 32781,
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("std:6", assetPaths({
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("std:8", assetPaths({
  {
      dest = 1,
      op = "bufferitemname",
      src = 32768,
    },
  {
      [1] = 32768,
      op = "checkitemtype",
    },
  {
      op = "call",
      target = "EventScript_BufferPocketName",
    },
  {
      dest = 0,
      op = "loadword",
      value = "Text_PutItemAway",
    },
  {
      op = "message",
      ptr = 0,
    },
  {
      op = "waitmessage",
    },
  {
      op = "waitbuttonpress",
    },
  {
      op = "return",
    },
}))
  mod.content.map_scripts:override("std:9", assetPaths({
  {
      [1] = 3,
      color = 3,
      op = "textcolor",
    },
  {
      op = "compare_var_to_value",
      value = 318,
      var = 32770,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_ReceivedItemFanfareKeyItem",
    },
  {
      op = "compare_var_to_value",
      value = 258,
      var = 32770,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_ReceivedItemFanfareItem",
    },
  {
      op = "compare_var_to_value",
      value = 257,
      var = 32770,
    },
  {
      cond = 1,
      op = "goto_if",
      target = "EventScript_ReceivedItemFanfareLevelUp",
    },
  {
      op = "goto",
      target = "EventScript_ReceivedItemFanfareDefault",
    },
}))
end
