-- generated by tools/content-editor (Gen 3).
return function(mod)
  if mod.generation ~= 3 then return end
  local function assetPaths(value)
    if type(value) ~= "table" then return value end
    for key, child in pairs(value) do
      if type(child) == "string" and tostring(key):match("^sprite") and child:sub(1,7) == "assets/" then
        value[key] = mod.path .. "/" .. child
      elseif type(child) == "table" then assetPaths(child) end
    end
    return value
  end
  mod.content.pokemon:patch("MEW", assetPaths({
  baseStats = {
    specialAttack = 113,
  },
  spriteFront = "assets/mew_front_inverted_64.png",
}))
  mod.content.map_scripts:register("EDITOR_TEST", assetPaths({
  {
      op = "end",
    },
}))
  local terrain = {
  FR_PALLET_TOWN = {
    [1025] = {
      coll = 0,
      elev = 3,
      mid = 1,
    },
  },
}
  local mapLayouts = {}
  mod.events:on("game.ready", function(ctx)
    local maps = ctx.game and ctx.game.data and ctx.game.data.maps or {}
    local Layout = require("src.core.game3.layout_native")
    local Space = require("src.core.game3.scripting.space")
    local bundle=Space.bundle
    local sourceLayouts={}
    for id,def in pairs(maps) do sourceLayouts[id]=def.midLayout end
    for id,spec in pairs(mapLayouts) do
      local def=maps[id]
      local base=sourceLayouts[spec.source or id]
      if def and base then
        setmetatable(base,Layout)
        local cells={}
        for y=0,spec.height-1 do for x=0,spec.width-1 do
          cells[y*spec.width+x+1]=(not spec.blank and x<base.width and y<base.height) and base:cellAt(x,y) or spec.fill or {mid=0,coll=255,elev=0}
        end end
        def.midLayout=Layout.fromDecoded({width=spec.width,height=spec.height,cells=cells,
          borderWidth=base.borderWidth,borderHeight=base.borderHeight,borderMids=base.borderMids},id,spec.pair or base.pair)
        def.width=spec.width;def.height=spec.height;def.pair=spec.pair or base.pair
      end
    end
    for id, edits in pairs(terrain) do
      local def = maps[id]
      if def then
        if bundle then
          bundle.events=bundle.events or {};local ev=bundle.events[id] or {};bundle.events[id]=ev
          for _,key in ipairs({"objects","bgEvents","coordEvents","mapScripts","music"}) do
            if def[key]~=nil then ev[key]=def[key] end
          end
        end
        local layout = def.midLayout
        if layout then
          -- Registry merges copy tables; restore the native layout methods.
          setmetatable(layout, Layout)
          layout.overrides = layout.overrides or {}
          for key, cell in pairs(edits) do
            layout:applyOverride(key % 1024, math.floor(key / 1024), cell.mid, cell.coll, cell.elev)
          end
        end
      end
    end
  end)
  local starterRules = {
  {
      level = 28,
      map = "FR_OAKS_LAB",
      matchSpecies = {
        "CHARMANDER",
        "MEW",
      },
      nickname = "EDITOR",
      onlyFirst = true,
      species = "MEW",
      variable = 16386,
    },
}
  local function starterContext(ctx, rule)
    local world = ctx and ctx.overworld
    local map = world and world.map
    local id = map and (map.gen3Id or map.id)
    local save = ctx and ctx.save
    if not (id and save) or id:gsub("^FR_", "") ~= rule.map:gsub("^FR_", "") then return false end
    return not rule.onlyFirst or (not (save.flags or {}).EVENT_GOT_STARTER and #(save.party or {}) == 0)
  end
  local function matches(rule, species)
    for _, name in ipairs(rule.matchSpecies) do if name == species then return true end end
    return false
  end
  local originalGifts = setmetatable({}, {__mode="k"})
  local selectedStarters = setmetatable({}, {__mode="k"})
  for _, rule in ipairs(starterRules) do
    local target = assert(mod.content.pokemon:get(rule.species), "Unknown starter species: " .. rule.species)
    local sourceIndices = {}
    for _, name in ipairs(rule.matchSpecies) do
      local rec = assert(mod.content.pokemon:get(name), "Unknown starter source: " .. name)
      sourceIndices[rec.index] = true
    end

    mod.hooks:wrap("script.command", function(next, ctx, op, row)
      if rule.onlyFirst and not row._editorStarterChanged and op == "setvar" and (row.var or row[1]) == (rule.variable or 0x4002)
          and sourceIndices[row.value or row[2]] and starterContext(ctx, rule) then
        local copy = {}; for k,v in pairs(row) do copy[k]=v end
        copy.value,copy[2]=target.index,target.index
        copy._editorStarterChanged=true
        if rule.onlyFirst and ctx and ctx.save then selectedStarters[ctx.save]=rule end
        return next(ctx,op,copy)
      end
      if rule.egg and op=="giveegg" and sourceIndices[row.species or row[1]] and starterContext(ctx,rule) then
        local Party=require("src.core.game3.party")
        local Pokemon=require("src.core.game3.pokemon")
        local session=ctx.save
        local ok=false
        if #(session.party or {})<6 then
          -- Construct separately so an unhatched Egg is not registered in the Pokedex.
          local temp={party={},name=session.name,playerName=session.playerName,trainerId=session.trainerId}
          ok=Party.giveMon(temp,target.index,rule.level,rule.nickname)
          if ok then
            local egg=temp.party[1];egg.isEgg=true;egg.egg=true
            egg.friendship=(Pokemon.speciesMeta(target.index) or {}).eggCycles or 20;egg.eggCycles=egg.friendship
            session.party=session.party or {};table.insert(session.party,egg)
          end
        end
        local vm=ctx.vm or ctx.runner
        if vm and vm.store then require("src.core.game3.scripting.flags").setVar(vm.store,vm.ctx,0x800D,ok and 0 or 2) end
        return true
      end
      return next(ctx,op,row)
    end)
    -- Run after handwritten gift listeners, preserving all unrelated gifts.
    mod.events:on("pokemon.before_give", function(gift)
      originalGifts[gift] = originalGifts[gift] or gift.species
      local selected = gift.ctx and gift.ctx.save and selectedStarters[gift.ctx.save]
      local match = rule.onlyFirst and selected and selected==rule and (matches(rule,originalGifts[gift]) or originalGifts[gift]==rule.species)
        or (not (rule.onlyFirst and selected) and matches(rule,originalGifts[gift]))
      if match and starterContext(gift.ctx,rule) then
        gift.species,gift.level=rule.species,rule.level
        if rule.nickname and rule.nickname~="" then gift.nickname=rule.nickname end
      end
    end,-1000)
  end
end
