-- generated by tools/content-editor (Gen 3).
return function(mod)
  if mod.generation ~= 3 then return end
  local function assetPaths(value)
    if type(value) ~= "table" then return value end
    for key, child in pairs(value) do
      if type(child) == "string" and tostring(key):match("^sprite") and child:sub(1,7) == "assets/" then
        value[key] = mod.path .. "/" .. child
      elseif type(child) == "table" then assetPaths(child) end
    end
    return value
  end
  mod.content.pokemon:register("UNOWN_FORM_10", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_10",
  index = 448,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_10/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_10/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_11", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_11",
  index = 449,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_11/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_11/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_12", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_12",
  index = 450,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_12/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_12/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_13", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_13",
  index = 451,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_13/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_13/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_14", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_14",
  index = 452,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_14/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_14/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_15", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_15",
  index = 453,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_15/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_15/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_16", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_16",
  index = 454,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_16/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_16/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_17", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_17",
  index = 455,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_17/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_17/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_18", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_18",
  index = 456,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_18/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_18/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_19", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_19",
  index = 457,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_19/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_19/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_2", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_2",
  index = 440,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_2/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_2/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_20", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_20",
  index = 458,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_20/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_20/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_21", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_21",
  index = 459,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_21/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_21/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_22", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_22",
  index = 460,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_22/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_22/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_23", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_23",
  index = 461,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_23/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_23/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_24", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_24",
  index = 462,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_24/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_24/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_25", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_25",
  index = 463,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_25/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_25/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_26", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_26",
  index = 464,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_26/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_26/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_27", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_27",
  index = 465,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_27/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_27/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_28", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_28",
  index = 466,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_28/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_28/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_3", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_3",
  index = 441,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_3/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_3/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_4", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_4",
  index = 442,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_4/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_4/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_5", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_5",
  index = 443,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_5/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_5/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_6", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_6",
  index = 444,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_6/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_6/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_7", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_7",
  index = 445,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_7/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_7/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_8", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_8",
  index = 446,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_8/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_8/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  mod.content.pokemon:register("UNOWN_FORM_9", assetPaths({
  abilities = {
    "LEVITATE",
  },
  baseExp = 61,
  baseStats = {
    attack = 72,
    defense = 48,
    hp = 48,
    specialAttack = 72,
    specialDefense = 48,
    speed = 48,
  },
  catchRate = 225,
  dex = 201,
  dexEntry = {
    height = 5,
    kind = "SYMBOL",
    weight = 50,
  },
  eggCycles = 40,
  eggGroups = { 15, 15 },
  evolutions = {},
  friendship = 70,
  genderRatio = 255,
  growthRate = "MEDIUM_FAST",
  id = "UNOWN_FORM_9",
  index = 447,
  learnset = {
    {
          level = 1,
          move = "HIDDEN_POWER",
        },
  },
  name = "UNOWN",
  spriteBack = "assets/forms/UNOWN_FORM_9/spriteBack.png",
  spriteFront = "assets/forms/UNOWN_FORM_9/spriteFront.png",
  tmhm = {},
  trueColor = true,
  types = {
    "PSYCHIC",
  },
}))
  do local value = {}; for k,v in pairs(mod.content.encounters:get("FR_ROUTE_1") or {}) do value[k]=v end
    for k,v in pairs(assetPaths({
  land = {
    rate = 21,
    slots = {
      {
              maxLevel = 3,
              minLevel = 3,
              species = "UNOWN_FORM_11",
            },
      {
              maxLevel = 3,
              minLevel = 3,
              species = "RATTATA",
            },
      {
              maxLevel = 3,
              minLevel = 3,
              species = "UNOWN_FORM_10",
            },
      {
              maxLevel = 3,
              minLevel = 3,
              species = "RATTATA",
            },
      {
              maxLevel = 2,
              minLevel = 2,
              species = "AERODACTYL",
            },
      {
              maxLevel = 2,
              minLevel = 2,
              species = "RATTATA",
            },
      {
              maxLevel = 3,
              minLevel = 3,
              species = "UNOWN_FORM_15",
            },
      {
              maxLevel = 3,
              minLevel = 3,
              species = "RATTATA",
            },
      {
              maxLevel = 4,
              minLevel = 4,
              species = "UNOWN_FORM_27",
            },
      {
              maxLevel = 4,
              minLevel = 4,
              species = "RATTATA",
            },
      {
              maxLevel = 5,
              minLevel = 5,
              species = "UNOWN_FORM_26",
            },
      {
              maxLevel = 4,
              minLevel = 4,
              species = "RATTATA",
            },
    },
  },
  mapGroup = 3,
  mapNum = 19,
})) do value[k]=v end
    mod.content.encounters:override("FR_ROUTE_1",value) end
  do local value = {}; for k,v in pairs(mod.content.maps:get("FR_PLAYERS_HOUSE_2F") or {}) do value[k]=v end
    for k,v in pairs(assetPaths({
  bgEvents = {
    {
          elevation = 3,
          kind = 0,
          scriptKey = "g3:08168cd2",
          scriptPtr = 135695570,
          type = "sign",
          x = 6,
          y = 5,
        },
    {
          elevation = 0,
          kind = 0,
          scriptKey = "g3:08168ce4",
          scriptPtr = 135695588,
          type = "sign",
          x = 1,
          y = 1,
        },
    {
          elevation = 0,
          kind = 0,
          scriptKey = "g3:08168cdb",
          scriptPtr = 135695579,
          type = "sign",
          x = 11,
          y = 1,
        },
  },
  connections = {},
  coordEvents = {},
  environment = "INDOOR",
  id = "FR_PLAYERS_HOUSE_2F",
  kind = "indoor",
  label = "FR_PLAYERS_HOUSE_2F",
  mapScripts = {
    onFrame = {},
    onResume = {},
    onTransition = "g3:08168cae",
  },
  music = 300,
  name = "FR_PLAYERS_HOUSE_2F",
  objects = {},
  pair = "player_house",
  trueColor = true,
  warps = {
    {
          destMap = "FR_PLAYERS_HOUSE_1F",
          destWarp = 3,
          disabled = false,
          x = 10,
          y = 2,
        },
  },
})) do value[k]=v end
    mod.content.maps:override("FR_PLAYERS_HOUSE_2F",value) end
  local terrain = {
  FR_PLAYERS_HOUSE_2F = {},
}
  local mapLayouts = {}
  mod.events:on("game.ready", function(ctx)
    local maps = ctx.game and ctx.game.data and ctx.game.data.maps or {}
    local Layout = require("src.core.game3.layout_native")
    local Space = require("src.core.game3.scripting.space")
    local bundle=Space.bundle
    local sourceLayouts={}
    for id,def in pairs(maps) do sourceLayouts[id]=def.midLayout end
    for id,spec in pairs(mapLayouts) do
      local def=maps[id]
      local base=sourceLayouts[spec.source or id]
      if def and base then
        setmetatable(base,Layout)
        local cells={}
        for y=0,spec.height-1 do for x=0,spec.width-1 do
          cells[y*spec.width+x+1]=(not spec.blank and x<base.width and y<base.height) and base:cellAt(x,y) or spec.fill or {mid=0,coll=255,elev=0}
        end end
        def.midLayout=Layout.fromDecoded({width=spec.width,height=spec.height,cells=cells,
          borderWidth=base.borderWidth,borderHeight=base.borderHeight,borderMids=base.borderMids},id,spec.pair or base.pair)
        def.width=spec.width;def.height=spec.height;def.pair=spec.pair or base.pair
      end
    end
    for id, edits in pairs(terrain) do
      local def = maps[id]
      if def then
        if bundle then
          bundle.events=bundle.events or {};local ev=bundle.events[id] or {};bundle.events[id]=ev
          for _,key in ipairs({"objects","bgEvents","coordEvents","mapScripts","music"}) do
            if def[key]~=nil then ev[key]=def[key] end
          end
        end
        local layout = def.midLayout
        if layout then
          -- Registry merges copy tables; restore the native layout methods.
          setmetatable(layout, Layout)
          layout.overrides = layout.overrides or {}
          for key, cell in pairs(edits) do
            layout:applyOverride(key % 1024, math.floor(key / 1024), cell.mid, cell.coll, cell.elev)
          end
        end
      end
    end
  end)
  local starterRules = {
  {
      level = 5,
      map = "FR_OAKS_LAB",
      matchSpecies = {
        "BULBASAUR",
      },
      nickname = "",
      onlyFirst = true,
      species = "SCIZOR",
      variable = 16386,
    },
  {
      level = 5,
      map = "FR_OAKS_LAB",
      matchSpecies = {
        "CHARMANDER",
      },
      nickname = "",
      onlyFirst = true,
      species = "CHARMANDER",
      variable = 16386,
    },
  {
      level = 5,
      map = "FR_OAKS_LAB",
      matchSpecies = {
        "SQUIRTLE",
      },
      nickname = "",
      onlyFirst = true,
      species = "SQUIRTLE",
      variable = 16386,
    },
}
  local function starterContext(ctx, rule)
    local world = ctx and ctx.overworld
    local map = world and world.map
    local id = map and (map.gen3Id or map.id)
    local save = ctx and ctx.save
    if not (id and save) or id:gsub("^FR_", "") ~= rule.map:gsub("^FR_", "") then return false end
    return not rule.onlyFirst or (not (save.flags or {}).EVENT_GOT_STARTER and #(save.party or {}) == 0)
  end
  local function matches(rule, species)
    for _, name in ipairs(rule.matchSpecies) do if name == species then return true end end
    return false
  end
  local originalGifts = setmetatable({}, {__mode="k"})
  local selectedStarters = setmetatable({}, {__mode="k"})
  for _, rule in ipairs(starterRules) do
    local target = assert(mod.content.pokemon:get(rule.species), "Unknown starter species: " .. rule.species)
    local sourceIndices = {}
    for _, name in ipairs(rule.matchSpecies) do
      local rec = assert(mod.content.pokemon:get(name), "Unknown starter source: " .. name)
      sourceIndices[rec.index] = true
    end

    mod.hooks:wrap("script.command", function(next, ctx, op, row)
      if rule.onlyFirst and not row._editorStarterChanged and op == "setvar" and (row.var or row[1]) == (rule.variable or 0x4002)
          and sourceIndices[row.value or row[2]] and starterContext(ctx, rule) then
        local copy = {}; for k,v in pairs(row) do copy[k]=v end
        copy.value,copy[2]=target.index,target.index
        copy._editorStarterChanged=true
        if rule.onlyFirst and ctx and ctx.save then selectedStarters[ctx.save]=rule end
        return next(ctx,op,copy)
      end
      if rule.egg and op=="giveegg" and sourceIndices[row.species or row[1]] and starterContext(ctx,rule) then
        local Party=require("src.core.game3.party")
        local Pokemon=require("src.core.game3.pokemon")
        local session=ctx.save
        local ok=false
        if #(session.party or {})<6 then
          -- Construct separately so an unhatched Egg is not registered in the Pokedex.
          local temp={party={},name=session.name,playerName=session.playerName,trainerId=session.trainerId}
          ok=Party.giveMon(temp,target.index,rule.level,rule.nickname)
          if ok then
            local egg=temp.party[1];egg.isEgg=true;egg.egg=true
            egg.friendship=(Pokemon.speciesMeta(target.index) or {}).eggCycles or 20;egg.eggCycles=egg.friendship
            session.party=session.party or {};table.insert(session.party,egg)
          end
        end
        local vm=ctx.vm or ctx.runner
        if vm and vm.store then require("src.core.game3.scripting.flags").setVar(vm.store,vm.ctx,0x800D,ok and 0 or 2) end
        return true
      end
      return next(ctx,op,row)
    end)
    -- Run after handwritten gift listeners, preserving all unrelated gifts.
    mod.events:on("pokemon.before_give", function(gift)
      originalGifts[gift] = originalGifts[gift] or gift.species
      local selected = gift.ctx and gift.ctx.save and selectedStarters[gift.ctx.save]
      local match = rule.onlyFirst and selected and selected==rule and (matches(rule,originalGifts[gift]) or originalGifts[gift]==rule.species)
        or (not (rule.onlyFirst and selected) and matches(rule,originalGifts[gift]))
      if match and starterContext(gift.ctx,rule) then
        gift.species,gift.level=rule.species,rule.level
        if rule.nickname and rule.nickname~="" then gift.nickname=rule.nickname end
      end
    end,-1000)
  end
local introAssets=(function()
-- Boot loads PNGs directly through LÖVE, bypassing CacheFs overrides.
local M={}
function M.install(mod,assets)
  local RT=require("src.mods.Runtime");local Boot=require("src.ui.game3.boot")
  local images={};local token={}
  local aliases={oak="oakSprite",boy="boySprite",girl="girlSprite",rival="rivalSprite",nidoran_f="nidoranFront",pikachu_intro_bg="pikachuBg",title_border_bg="titleBorder"}
  local stateKeys={title_screen="titleScreen",title_logo="titleLogo",box_art_mon="titleMon",title_border_bg="titleBorder",press_start="pressStart",copyright_press_start="copyrightLayer"}
  local function apply(state)
    if state._editorIntroAssets==token then return end
    state.assets=state.assets or {}
    for path,rec in pairs(assets) do
      local name=path:match("^data/generated/gba/intro/([^/]+)%.png$")
      if name then
        if not images[path] then
          images[path]=love.graphics.newImage(love.filesystem.newFileData(assert(mod:read(rec.file)),"intro.png"));images[path]:setFilter("nearest","nearest")
        end
        local img=images[path];state.assets[aliases[name] or name:gsub("_(%w)",string.upper)]=img
        if stateKeys[name] then state[stateKeys[name]]=img end
        if name=="platform" then state.assets.platformQuad=love.graphics.newQuad(0,0,32,32,img:getDimensions()) end
      end
    end
    state._editorIntroAssets=token
  end
  local function bridge(t,key,hook)
    t._editorIntroBridges=t._editorIntroBridges or {};if t._editorIntroBridges[key] then return end;t._editorIntroBridges[key]=true
    local original=t[key];t[key]=function(...) return RT.call(hook,original,...) end
  end
  bridge(Boot,"new","editor.gen3.intro.new");bridge(Boot,"update","editor.gen3.intro.update")
  bridge(require("src.ui.game3.title_screen"),"enter","editor.gen3.intro.title")
  mod.hooks:wrap("editor.gen3.intro.new",function(proceed,...) local state=proceed(...);apply(state);return state end)
  mod.hooks:wrap("editor.gen3.intro.update",function(proceed,state,...) apply(state);return proceed(state,...) end)
  mod.hooks:wrap("editor.gen3.intro.title",function(proceed,state,...) apply(state);return proceed(state,...) end)
end
return M

end)()
introAssets.install(mod,{
  ["data/generated/gba/intro/title_border_bg.png"] = {
    file = "assets/gen3/intro/title_border_bg.png",
    height = 160,
    width = 240,
  },
})
local forms=(function()
local M={}
function M.choose(f,personality)
  local p=tonumber(personality) or 0
  if f.mode=="unown" then
    local bit=require("bit")
    local letter=bit.bor(bit.rshift(bit.band(p,0x03000000),18),bit.rshift(bit.band(p,0x00030000),12),bit.rshift(bit.band(p,0x00000300),6),bit.band(p,3))%28
    return letter%#f.forms+1
  elseif f.mode=="personality" then return p%#f.forms+1 end
  return math.max(1,math.min(#f.forms,f.default or 1))
end
function M.install(mod,configs)
  local Runtime=require("src.mods.Runtime");local P=require("src.core.game3.pokemon")
  local families,parents,records,pictures={},{},{},{}
  for _,f in ipairs(configs) do
    local parent=assert(mod.content.pokemon:get(f.parent),"Missing form parent "..f.parent);f.index=parent.index;parents[parent.index]=f
    for _,row in ipairs(f.forms) do local rec=assert(mod.content.pokemon:get(row.species),"Missing form "..row.species);row.index=rec.index;families[rec.index]=f;records[rec.index]=rec end
  end
  local function bridge(object,name,key)
    if object[key] then return end;object[key]=true;local original=object[name]
    object[name]=function(...) return Runtime.call(key,original,...) end
  end
  -- FireRed installs its ROM tables again when starting a game. Reapply the
  -- merged registry then, rather than leaving custom form IDs without data.
  local registry,encounterRegistry
  local E=require("src.core.game3.encounters")
  local function restoreEncounters()
    if not encounterRegistry then return end
    for id in pairs(encounterRegistry.ops) do
      local source=encounterRegistry:get(id)
      if source then
        for key,target in pairs(E._tables) do
          if key==id or (source.mapGroup~=nil and source.mapNum~=nil and target.mapGroup==source.mapGroup and target.mapNum==source.mapNum) then
            for _,kind in ipairs({"land","grass","water","rocks","fishing"}) do
              local from,to=source[kind],target[kind]
              if from and to then
                from=from.slots or from.mons or from;to=to.slots or to.mons or to
                for i,slot in ipairs(from) do
                  local rec=mod.content.pokemon:get(slot.species or slot[1])
                  if rec and families[rec.index] and to[i] then
                    if to[i].species~=nil then to[i].species=rec.index else to[i][1]=rec.index end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
  local function restore()
    if registry and P._names then registry.spec.write(P,registry) end
    pictures={}
  end
  mod.events:on("mods.loaded",function(ev)
    registry=ev.loader.content.pokemon
    encounterRegistry=ev.loader.content.encounters
    restore()
    restoreEncounters()
  end)
  bridge(E,"ensureLoaded","editor.gen3.forms.encounters")
  mod.hooks:wrap("editor.gen3.forms.encounters",function(proceed,...)
    local result=proceed(...);restoreEncounters();return result
  end)
  bridge(P,"keyName","editor.gen3.forms.key")
  mod.hooks:wrap("editor.gen3.forms.key",function(proceed,species)
    local rec=records[tonumber(species)];return rec and rec.id or proceed(species)
  end)
  bridge(P,"speciesFromName","editor.gen3.forms.lookup")
  mod.hooks:wrap("editor.gen3.forms.lookup",function(proceed,id)
    for index,rec in pairs(records) do if rec.id==id then return index end end
    return proceed(id)
  end)
  mod.hooks:wrap("editor.gen3.forms.reload",function(proceed,...) proceed(...);restore() end)
  P.onReload(function() Runtime.call("editor.gen3.forms.reload",function() end) end,"editor.gen3.forms")
  local function assign(mon)
    if type(mon)~="table" then return end
    local species=tonumber(mon.species or mon.speciesId);local f=parents[species]
    if not f or f.mode=="weather" or mon._editorFormAssigned==f.parent then return end
    local row=f.forms[M.choose(f,mon.personality)]
    mon.species=row.index;mon.speciesId=row.index;mon._editorFormAssigned=f.parent
    mon.ability=P.abilityId(row.index,mon.personality or 0);mon.abilityId=mon.ability
    return row.index~=species
  end
  for _,side in ipairs({"front","back"}) do
    local method=side.."Pic";local hook="editor.gen3.forms."..side
    bridge(P,method,hook)
    mod.hooks:wrap(hook,function(proceed,species,form)
      local rec=records[tonumber(species)]
      local path=rec and rec[side=="front" and "spriteFront" or "spriteBack"]
      if path and not path:match("^data/generated/") then
        if not pictures[path] then
          local img=love.graphics.newImage(path);img:setFilter("nearest","nearest")
          pictures[path]={image=img,w=img:getWidth(),h=img:getHeight()}
        end
        return pictures[path]
      end
      local entry=proceed(species,form);local f=families[tonumber(species)]
      if not entry and f and tonumber(species)~=f.index then return proceed(f.index,0) end
      return entry
    end)
  end
  local Party=require("src.core.game3.party")
  local Battle=require("src.core.game3.battle")
  bridge(Battle,"start","editor.gen3.forms.battleMoves")
  mod.hooks:wrap("editor.gen3.forms.battleMoves",function(proceed,opts)
    if not opts or not opts.foe then return proceed(opts) end
    local clone=require("src.mods.Merge").deepCopy
    local copy={};for k,v in pairs(opts) do copy[k]=v end
    copy.foe=clone(opts.foe)
    if opts.foeParty then copy.foeParty=clone(opts.foeParty) end
    local function prepare(foe)
      if type(foe)~="table" or (foe.moves and #foe.moves>0) then return end
      if foe.personality==nil then foe.personality=require("src.core.game3.rng").Random32() end
      assign(foe)
      local moves,pp,maxPp=P.movesAtLevel(foe.species or foe.id,foe.level or 5)
      if #moves>0 then foe.moves=moves;foe.pp=pp;foe.maxPp=maxPp end
    end
    prepare(copy.foe)
    for _,foe in ipairs(copy.foe.party or {}) do prepare(foe) end
    for _,foe in ipairs(copy.foeParty or {}) do prepare(foe) end
    return proceed(copy)
  end)
  bridge(P,"icon","editor.gen3.forms.icon")
  mod.hooks:wrap("editor.gen3.forms.icon",function(proceed,species)
    local entry=proceed(species);local f=families[tonumber(species)]
    if not entry and f and tonumber(species)~=f.index then return proceed(f.index) end
    return entry
  end)
  bridge(Party,"giveMon","editor.gen3.forms.gift")
  mod.hooks:wrap("editor.gen3.forms.gift",function(proceed,session,species,level,nickname)
    local f=parents[tonumber(species)]
    if f and f.mode=="fixed" then species=f.forms[M.choose(f,0)].index end
    return proceed(session,species,level,nickname)
  end)
  bridge(P,"applyStats","editor.gen3.forms.stats")
  mod.hooks:wrap("editor.gen3.forms.stats",function(proceed,mon) assign(mon);return proceed(mon) end)
  local State=require("src.core.game3.battle.state")
  bridge(State,"makeBattler","editor.gen3.forms.battler")
  mod.hooks:wrap("editor.gen3.forms.battler",function(proceed,mon,...)
    if assign(mon) then P.applyStats(mon) end
    return proceed(mon,...)
  end)
  local Abilities=require("src.core.game3.battle.abilities")
  bridge(Abilities,"castformChange","editor.gen3.forms.weather")
  mod.hooks:wrap("editor.gen3.forms.weather",function(proceed,ad,b)
    local f=b and families[tonumber(b.species)]
    if not f or f.mode~="weather" then return proceed(ad,b) end
    if ad:hp(b)<=0 or ad:abilityOf(b)~="FORECAST" then return 0 end
    local weather=require("src.core.game3.battle.rules").weather.effective(ad._st,ad)
    local selected=f.forms[1]
    for i,row in ipairs(f.forms) do if i>1 and row.weather==weather then selected=row;break end end
    -- Battle appearance and typing are temporary. The saved Pokemon retains its identity and stats.
    if b._editorWeatherIndex~=selected.index then
      local types=P.types(selected.index);b.species=selected.index;b.type1=types[1];b.type2=types[2]~=types[1] and types[2] or nil;b._editorWeatherIndex=selected.index
    end
    return 0
  end)
end
return M

end)()
forms.install(mod,{
  {
      default = 1,
      forms = {
        {
                name = "A",
                species = "UNOWN",
              },
        {
                name = "B",
                species = "UNOWN_FORM_2",
              },
        {
                name = "C",
                species = "UNOWN_FORM_3",
              },
        {
                name = "D",
                species = "UNOWN_FORM_4",
              },
        {
                name = "E",
                species = "UNOWN_FORM_5",
              },
        {
                name = "F",
                species = "UNOWN_FORM_6",
              },
        {
                name = "G",
                species = "UNOWN_FORM_7",
              },
        {
                name = "H",
                species = "UNOWN_FORM_8",
              },
        {
                name = "I",
                species = "UNOWN_FORM_9",
              },
        {
                name = "J",
                species = "UNOWN_FORM_10",
              },
        {
                name = "K",
                species = "UNOWN_FORM_11",
              },
        {
                name = "L",
                species = "UNOWN_FORM_12",
              },
        {
                name = "M",
                species = "UNOWN_FORM_13",
              },
        {
                name = "N",
                species = "UNOWN_FORM_14",
              },
        {
                name = "O",
                species = "UNOWN_FORM_15",
              },
        {
                name = "P",
                species = "UNOWN_FORM_16",
              },
        {
                name = "Q",
                species = "UNOWN_FORM_17",
              },
        {
                name = "R",
                species = "UNOWN_FORM_18",
              },
        {
                name = "S",
                species = "UNOWN_FORM_19",
              },
        {
                name = "T",
                species = "UNOWN_FORM_20",
              },
        {
                name = "U",
                species = "UNOWN_FORM_21",
              },
        {
                name = "V",
                species = "UNOWN_FORM_22",
              },
        {
                name = "W",
                species = "UNOWN_FORM_23",
              },
        {
                name = "X",
                species = "UNOWN_FORM_24",
              },
        {
                name = "Y",
                species = "UNOWN_FORM_25",
              },
        {
                name = "Z",
                species = "UNOWN_FORM_26",
              },
        {
                name = "!",
                species = "UNOWN_FORM_27",
              },
        {
                name = "?",
                species = "UNOWN_FORM_28",
              },
      },
      mode = "unown",
      parent = "UNOWN",
    },
})
local fly=(function()
local M={}
function M.available(row,session,visited)
  if row.enabled==false then return false end
  if row.unlock=="always" then return true end
  if row.unlock=="flag" then
    return require("src.core.game3.scripting.flags").getFlag(session,nil,row.flag)
  end
  return session.map==row.map or visited[row.map]==true
end
function M.install(mod,rows)
  local Runtime=require("src.mods.Runtime")
  local Field=require("src.core.game3.field")
  local Region=require("src.ui.game3.region_map")
  local function bridge(object,name,key)
    if object[key] then return end
    object[key]=true;local original=object[name]
    object[name]=function(...) return Runtime.call(key,original,...) end
  end
  bridge(Field,"executeFieldMove","editor.gen3.fly")
  for _,name in ipairs({"show","close","handleInput","draw","currentLocationName"}) do bridge(Region,name,"editor.gen3.fly."..name) end
  local active,index=nil,1
  local function visited(session)
    session.modData=session.modData or {};session.modData[mod.id]=session.modData[mod.id] or {}
    local data=session.modData[mod.id];data.flyVisited=data.flyVisited or {};return data.flyVisited
  end
  mod.events:on("map.entered",function(e)
    local session=Field.getSession();if session then visited(session)[e.mapId]=true end
  end)
  local function selectRow() local row=active and active[index];if row then Region.cursorX=row.mapX;Region.cursorY=row.mapY end end
  mod.hooks:wrap("editor.gen3.fly.show",function(proceed,opts) active=nil;return proceed(opts) end)
  mod.hooks:wrap("editor.gen3.fly.close",function(proceed,...) active=nil;return proceed(...) end)
  mod.hooks:wrap("editor.gen3.fly",function(proceed,payload)
    if not payload or payload.action~="fly" then return proceed(payload) end
    local session=Field.getSession();if not session then return end
    local choices={};for _,row in ipairs(rows) do if M.available(row,session,visited(session)) then choices[#choices+1]=row end end
    if #choices==0 then
      local Message=require("src.ui.game3.message")
      Message.show("Visit a Fly destination first.",function() Message.close() end);return
    end
    Region.show({session=session});active=choices;index=1;selectRow()
  end)
  mod.hooks:wrap("editor.gen3.fly.currentLocationName",function(proceed)
    return active and active[index].name or proceed()
  end)
  mod.hooks:wrap("editor.gen3.fly.handleInput",function(proceed,input)
    if not active then return proceed(input) end
    if input:wasPressed("b") or input:wasPressed("start") then Region.close();return end
    if input:wasPressed("a") then
      local row=active[index];Region.close()
      local Map=require("src.core.game3.map");local Player=require("src.core.game3.player")
      Map.load(Field._mod,Field._game,row.map,{x=row.x,y=row.y,facing="down",depth1Connections=true,via="fly"})
      Player.reset(row.x,row.y,"down");Player.syncToHost(Field._game)
      return
    end
    local delta=(input:wasPressed("right") or input:wasPressed("down")) and 1 or (input:wasPressed("left") or input:wasPressed("up")) and -1 or 0
    index=(index-1+delta)%#active+1;selectRow()
  end)
  mod.hooks:wrap("editor.gen3.fly.draw",function(proceed)
    proceed();if not active then return end
    love.graphics.push("all")
    for i,row in ipairs(active) do
      love.graphics.setColor(i==index and 1 or .2,1,.2,1)
      love.graphics.rectangle("line",36+row.mapX*8,24+row.mapY*8,8,8)
    end
    love.graphics.setColor(.12,.22,.18,1);love.graphics.rectangle("fill",0,144,240,16)
    require("src.ui.game3.frlg_font").draw("D-PAD: SELECT  A: FLY  B: BACK",4,146,{color={1,1,1,1},small=true})
    love.graphics.pop()
  end)
end
return M

end)()
fly.install(mod,{
  {
      enabled = true,
      map = "FR_PALLET_TOWN",
      mapX = 4,
      mapY = 11,
      name = "PALLET TOWN",
      unlock = "visited",
      x = 6,
      y = 8,
    },
  {
      enabled = true,
      map = "FR_VIRIDIAN_CITY",
      mapX = 4,
      mapY = 8,
      name = "VIRIDIAN CITY",
      unlock = "visited",
      x = 26,
      y = 27,
    },
  {
      enabled = true,
      map = "FR_PEWTER_CITY",
      mapX = 4,
      mapY = 4,
      name = "PEWTER CITY",
      unlock = "visited",
      x = 17,
      y = 26,
    },
  {
      enabled = true,
      map = "FR_CERULEAN_CITY",
      mapX = 14,
      mapY = 3,
      name = "CERULEAN CITY",
      unlock = "visited",
      x = 22,
      y = 20,
    },
  {
      enabled = true,
      map = "FR_LAVENDER_TOWN",
      mapX = 18,
      mapY = 6,
      name = "LAVENDER TOWN",
      unlock = "visited",
      x = 6,
      y = 6,
    },
  {
      enabled = true,
      map = "FR_VERMILION_CITY",
      mapX = 14,
      mapY = 9,
      name = "VERMILION CITY",
      unlock = "visited",
      x = 15,
      y = 7,
    },
  {
      enabled = true,
      map = "FR_CELADON_CITY",
      mapX = 11,
      mapY = 6,
      name = "CELADON CITY",
      unlock = "visited",
      x = 48,
      y = 12,
    },
  {
      enabled = true,
      map = "FR_FUCHSIA_CITY",
      mapX = 12,
      mapY = 12,
      name = "FUCHSIA CITY",
      unlock = "visited",
      x = 25,
      y = 32,
    },
  {
      enabled = true,
      map = "FR_CINNABAR_ISLAND",
      mapX = 4,
      mapY = 14,
      name = "CINNABAR ISLAND",
      unlock = "visited",
      x = 14,
      y = 12,
    },
  {
      enabled = true,
      map = "FR_INDIGO_PLATEAU_EXTERIOR",
      mapX = 2,
      mapY = 3,
      name = "INDIGO PLATEAU",
      unlock = "visited",
      x = 11,
      y = 7,
    },
  {
      enabled = true,
      map = "FR_SAFFRON_CITY",
      mapX = 14,
      mapY = 6,
      name = "SAFFRON CITY",
      unlock = "visited",
      x = 24,
      y = 39,
    },
  {
      enabled = true,
      map = "FR_ROUTE4",
      mapX = 11,
      mapY = 3,
      name = "ROUTE4",
      unlock = "visited",
      x = 12,
      y = 6,
    },
  {
      enabled = true,
      map = "FR_ROUTE10",
      mapX = 18,
      mapY = 5,
      name = "ROUTE10",
      unlock = "visited",
      x = 13,
      y = 21,
    },
})
  local oakScene=(function()
local M={}
function M.configure(scene,settings,lines)
  settings=settings or {};scene._editorOakSettings=settings
  if settings.species then
    local picture=require("src.core.game3.pokemon").frontPic(settings.species)
    if picture then local assets={};for k,v in pairs(scene.assets) do assets[k]=v end;assets.nidoranFront=picture.image;scene.assets=assets end
  end
  if settings.textSpeed then scene.textSpeedOption=settings.textSpeed;scene.textSpeed=({[0]=8,4,1})[settings.textSpeed] end
  if settings.skipGuides then
    scene.bgVisible[0],scene.bgVisible[1]=true,true
    scene.tasks={};local task=scene:createTask(require("src.ui.game3.new_game_scene").Task_OakSpeech_Init,0);task.data.timer=0
  end
  if lines then
    local original=scene.oakPrint
    scene.oakPrint=function(self,key,speed) return original(self,lines[key] or key,speed) end
  end
  local frame=scene.frame
  scene.frame=function(self,...)
    local Audio=require("src.core.game3.audio");local cry=Audio.playCry
    Audio.playCry=function(species,...) return cry(species==29 and settings.species or species,...) end
    local result={pcall(frame,self,...)};Audio.playCry=cry
    if not result[1] then error(result[2]) end
    return unpack(result,2)
  end
  return scene
end
function M.install(mod,settings)
  local Scene=require("src.ui.game3.new_game_scene");local Runtime=require("src.mods.Runtime")
  if not Scene._editorOakScene then Scene._editorOakScene=true;local base=Scene.new
    Scene.new=function(...) return Runtime.call("editor.gen3.oakScene",base,...) end
  end
  mod.hooks:wrap("editor.gen3.oakScene",function(proceed,...)
    return M.configure(proceed(...),settings)
  end)
end
return M

end)()
  oakScene.install(mod,{
  skipGuides = true,
  species = 151,
  textSpeed = 2,
})
  local oakLines={}
  local Scene=require("src.ui.game3.new_game_scene")
  local Runtime=require("src.mods.Runtime")
  if not Scene._editorOakBridge then
    Scene._editorOakBridge=true;local original=Scene.oakPrint
    Scene.oakPrint=function(self,key,speed) return Runtime.call("editor.gen3.oakPrint",original,self,key,speed) end
  end
  mod.hooks:wrap("editor.gen3.oakPrint",function(proceed,scene,key,speed)
    return proceed(scene,oakLines[key] or key,speed)
  end)

  local native = {
  animations = {},
  assets = {
    ["data/generated/gba/intro/title_border_bg.png"] = {
      file = "assets/gen3/intro/title_border_bg.png",
      height = 160,
      width = 240,
    },
  },
  audio = {},
  help = {},
  items = {},
}
  local Runtime = require("src.mods.Runtime")
  local Cache = require("src.import.CacheFs")
  local function invalidateNativeImages()
    local cache=require("src.core.game3.dataset").cache()
    local Anim=require("src.core.game3.battle.anim")
    Anim._packLoaded=false;Anim._pack=nil
    for _,name in ipairs({"party_chrome","bag_chrome","battle_chrome","battle_transition_chrome","pokedex_chrome","summary_chrome","shop_chrome","naming_chrome"}) do
      local module=require("src.ui.game3."..name)
      if module.install then module.install(cache) end
    end
    local TrainerPic=require("src.core.game3.trainer_pic");TrainerPic._front={};TrainerPic._back={}
    require("src.core.game3.items_data").install(cache)
    require("src.ui.game3.help_system").install(cache)
    local map=require("src.ui.game3.region_map");map._images={}
    local bytes=cache:read("data/generated/gba/region_map/kanto_map.png")
    if bytes and love and love.graphics then
      local ok,img=pcall(function() return love.graphics.newImage(love.filesystem.newFileData(bytes,"map.png")) end)
      if ok then img:setFilter("nearest","nearest");map._images.kanto_map=img end
    end
    require("src.ui.game3.chrome").invalidate()
    require("src.ui.game3.frlg_font").invalidate()
    require("src.core.game3.ow_sprites").install(cache)
    require("src.core.game3.tileset_native").install(cache)
    require("src.core.game3.field_effects").install(cache)
  end
  if not Runtime._contentEditorLifecycle then
    Runtime._contentEditorLifecycle=true
    for _,name in ipairs({"install","reset"}) do
      local original=Runtime[name]
      Runtime[name]=function(...)
        original(...)
        if Cache._contentEditorInvalidate then
          local reset=Cache._contentEditorInvalidate;Cache._contentEditorInvalidate=nil;reset()
        end
      end
    end
  end
  if next(native.items) or next(native.help) or next(native.assets) or next(native.animations) then Cache._contentEditorInvalidate=invalidateNativeImages end
  -- One process-wide dispatcher; callbacks belong to the loader and disappear
  -- on disable/reload. Never overwrite the extracted cache on disk.
  if not Cache._contentEditorBridge then
    Cache._contentEditorBridge = true
    local read = Cache.read
    Cache.read = function(path) return Runtime.call("editor.gen3.cache", read, path) end
  end
  local function encode(v)
    if type(v)=="string" then return string.format("%q",v) end
    if type(v)~="table" then return tostring(v) end
    local parts={"{"}
    for k,c in pairs(v) do parts[#parts+1]="["..encode(k).."]="..encode(c).."," end
    parts[#parts+1]="}";return table.concat(parts)
  end
  local memo={}
  mod.hooks:wrap("editor.gen3.cache",function(proceed,path)
    local key=path:gsub("^firered/","")
    if not key:match("^data/generated/gba/") then key="data/generated/gba/"..key end
    local asset=native.assets[key]
    if asset then
      if not memo[key] then memo[key]=assert(mod:read(asset.file),"Missing native asset "..asset.file) end
      return memo[key]
    end
    local bytes=proceed(path)
    if key=="data/generated/gba/pokemon/battle_anims/pack.lua" and next(native.animations) then
      if not memo[key] and bytes then
        local pack=assert(loadstring(bytes,"@animation-pack"))()
        for id,value in pairs(native.animations) do
          local section,k=id:match("^([^/]+)/(.+)$");k=tonumber(k) or k
          pack[section]=pack[section] or {};pack[section][k]=value
        end
        memo[key]="return "..encode(pack)
      end
      return memo[key] or bytes
    end
    if key=="data/generated/gba/items/pack.lua" and next(native.items) and bytes then
      if not memo[key] then
        local pack=assert(loadstring(bytes))()
        for _,row in pairs(native.items) do
          local index=tonumber(row.index);assert(index,"Item number missing")
          local entry=pack.items[index] or {};pack.items[index]=entry
          for k,v in pairs(row) do entry[k]=v end
          pack.count=math.max(pack.count or 0,index+1)
        end
        memo[key]="return "..encode(pack)
      end
      return memo[key]
    end
    if key=="data/generated/gba/help/pack.lua" and next(native.help) and bytes then
      if not memo[key] then
        local pack=assert(loadstring(bytes))()
        for id,row in pairs(native.help) do local g,n=id:match("^(%d+):(%d+)$");assert(g and n,"Invalid Help topic");pack.entries[tonumber(g)][tonumber(n)]=row end
        memo[key]="return "..encode(pack)
      end
      return memo[key]
    end
    return bytes
  end)
  mod.events:on("game.ready",function(ctx)
    local Dataset=require("src.core.game3.dataset")
    local cache=Dataset.cache()
    if next(native.animations) or next(native.assets) then
      local Anim=require("src.core.game3.battle.anim")
      Anim._packLoaded=false;Anim._pack=nil
    end
    if next(native.items) or next(native.help) or next(native.assets) then
      invalidateNativeImages()
    end
    for map,song in pairs(native.audio.mapSongs or {}) do
      if ctx.game.data.maps[map] then ctx.game.data.maps[map].music=song end
    end
  end)
  if next(native.audio) then
    local Audio=require("src.core.game3.audio")
    if not Audio._contentEditorBridge then
      Audio._contentEditorBridge=true
      for _,name in ipairs({"playSong","playSe","playCry","playFanfare"}) do
        local base=Audio[name]
        local function vanilla(...)
          if name=="playSong" and Audio._editorMusic then
            Audio._editorMusic:stop();Audio._editorMusic:release()
            if Audio._bgmSource==Audio._editorMusic then Audio._bgmSource=nil end
            Audio._editorMusic=nil
          end
          return base(...)
        end
        Audio[name]=function(...) return Runtime.call("editor.gen3.audio."..name,vanilla,...) end
      end
      local pump,pause,resume,finish=Audio.pumpBgm,Audio.pauseBgm,Audio.resumeBgm,Audio.endSession
      Audio.pumpBgm=function(...) if not Audio._editorMusic then return pump(...) end end
      Audio.pauseBgm=function(...)
        if not Audio._editorMusic then return pause(...) end
        Audio._bgmPaused=true;Audio._editorMusic:pause()
      end
      Audio.resumeBgm=function(...)
        if not Audio._editorMusic then return resume(...) end
        Audio._bgmPaused=false;Audio._editorMusic:play();Audio.applyGain()
      end
      Audio.endSession=function(...) local result=finish(...);Audio._editorMusic=nil;return result end
      local update=Audio.update
      Audio.update=function(...)
        if Audio._editorMusic and Audio._editorBus~=Runtime.hooks then
          Audio._editorMusic:stop();Audio._editorMusic:release()
          if Audio._bgmSource==Audio._editorMusic then Audio._bgmSource=nil end
          Audio._editorMusic=nil;Audio._currentSong=nil
        end
        return update(...)
      end
    end
    for _,entry in ipairs({{"playSong","songs"},{"playSe","sounds"},{"playCry","cries"},{"playFanfare","songs"}}) do
      local operation,section=entry[1],entry[2]
      mod.hooks:wrap("editor.gen3.audio."..operation,function(proceed,id,...)
        if operation=="playSong" and (id==nil or tonumber(id)==0 or tonumber(id)==65535) then return proceed(id,...) end
        if operation=="playSe" or operation=="playFanfare" then id=require("src.core.game3.se_ids").resolve(id) or id end
        local target=(native.audio[section] or {})[tostring(id)]
        if type(target)~="table" then return proceed(target~=nil and target or id,...) end
        local opts=select(1,...) or {}
        if operation=="playSong" and Audio._editorMusic and Audio._currentSong and Audio._currentSong.id==id and not opts.restart then return true end
        local source=love.audio.newSource(mod.assets:path(target.file),operation=="playSong" and "stream" or "static")
        source:setVolume(section=="songs" and (Audio._bgmVolume or 1) or (Audio._sfxVolume or 1))
        if operation=="playSong" then
          proceed(0)
          if Audio._bgmSource then Audio._bgmSource:release() end
          Audio._bgmSource=source;Audio._editorMusic=source;Audio._editorBus=Runtime.hooks
          Audio._currentSong={id=id,loop=target.loop~=false,duration=source:getDuration(),startedAt=os.clock()}
          Audio._bgmGen=id;Audio._bgmLocal=nil;Audio._bgmPaused=false;Audio._fadeIn=nil;Audio._fadeOut=nil
          source:setLooping(target.loop~=false)
          Audio.applyGain();Audio.applyBgmFilter()
        elseif operation=="playCry" then
          Audio.stopCry();Audio._crySource=source
          Audio._cryUntil=(Audio._cryClock or 0)+source:getDuration()*60
          Audio._duck=85/256;Audio._duckHold=2;Audio.applyGain()
        elseif operation=="playFanfare" then
          Audio._fanfareRestore=Audio._bgmGen;Audio.pauseBgm()
          Audio._fanfareActive=true;Audio._fanfareFrames=source:getDuration()*60
          Audio._fanfareSource=source
          Audio._seSources[#Audio._seSources+1]=source;Audio._seMeta[source]={id=tonumber(id) or id}
        else
          Audio._seSources[#Audio._seSources+1]=source;Audio._seMeta[source]={id=tonumber(id) or id,duckBgm=true}
        end
        source:play();return true
      end)
    end
  end

  local layered={
  animations = {
    building__rom_082d4c44 = {},
    oak_lab = {},
    player_house = {},
  },
  maps = {
    FR_PLAYERS_HOUSE_2F = {
      baseTileset = "player_house",
      cellHeight = 10,
      cellWidth = 12,
      collision = {
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "solid",
        "solid",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "solid",
        "walk",
        "walk",
        "solid",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "walk",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
        "solid",
      },
      gen3Border = {
        height = 2,
        mids = { 8, 8, 8, 8 },
        width = 2,
      },
      gen3Collision = {
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        130,
        7,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        7,
        114,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        7,
        0,
        0,
        7,
        0,
        7,
        0,
        0,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        7,
        0,
        7,
        0,
        0,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        7,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
      },
      gen3Elevation = {
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        0,
        3,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        0,
        3,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        0,
        0,
        3,
        0,
        3,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        0,
        4,
        0,
        4,
        0,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        0,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      },
      id = "FR_PLAYERS_HOUSE_2F",
      layers = {
        {
                  cells = {
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 647,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 43,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 44,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 32,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 150,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 655,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 134,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 48,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 51,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 52,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 40,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 40,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 21,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 40,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 40,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 166,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 663,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 90,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 56,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 59,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 60,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 5,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 6,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 7,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 646,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 13,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 14,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 15,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 643,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 644,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 645,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 67,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 68,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 53,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 68,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 70,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 651,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 652,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 653,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 83,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 75,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 654,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 78,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 86,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 659,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 660,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 661,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 83,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 69,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 662,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 69,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 86,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 91,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 92,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 92,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 92,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 94,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 8,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 9,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 1,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                    {
                                  source = "@runtime:player_house",
                                  tile = 0,
                                },
                  },
                  export = true,
                  id = "ground",
                  name = "Ground",
                  opacity = 1,
                  visible = true,
                },
      },
    },
  },
  sources = {},
}
  mod.events:on("game.ready",function(ctx)
    local T=require("src.core.game3.tileset_native")
    local Layout=require("src.core.game3.layout_native")
    local Interactions=require("src.core.game3.scripting.interaction_scripts")
    local View=require("src.core.game3.field_view")
    local Runtime=require("src.mods.Runtime")
    local Collision=require("src.core.game3.collision")
    if not Collision._editorWarpDispatch then
      Collision._editorWarpDispatch=true
      local install=Collision.installWarps
      Collision.installWarps=function(...) return Runtime.call("editor.gen3.warps.install",install,...) end
    end
    mod.hooks:wrap("editor.gen3.warps.install",function(proceed,map)
      proceed(map)
      for _,warp in ipairs(map and map.warps or {}) do
        if warp.disabled then Collision._warps[warp.y*1024+warp.x]=nil end
      end
    end)
    local built,images={},{}
    local function frameFor(ref)
      local pair=ref.source:match("^@runtime:(.+)$")
      local source=layered.sources[ref.source]
      local frames=pair and (layered.animations[pair] or {})[ref.tile] or source and (source.animations or {})[ref.tile]
      if not frames or #frames==0 then return ref.tile end
      local total=0;for _,f in ipairs(frames) do total=total+math.max(16,f.duration or 200) end
      local clock=love.timer.getTime()*1000%total
      for _,f in ipairs(frames) do clock=clock-math.max(16,f.duration or 200);if clock<0 then return f.tile end end
      return ref.tile
    end
    local function drawRef(ref,x,y,over)
      local pair=ref.source:match("^@runtime:(.+)$")
      local tile=frameFor(ref)
      love.graphics.setColor(1,1,1,ref.opacity or 1)
      if pair then
        local ts=assert(T.get(pair),"Missing native tileset "..pair)
        local image=ts.image
        if over then image=ts.overImage end
        if image then love.graphics.draw(image,over and T.overQuad(ts,T.slotFor(ts,tile)) or T.quad(ts,T.slotFor(ts,tile)),x,y) end
      elseif not over then
        local source=assert(layered.sources[ref.source],"Missing tile source "..ref.source)
        local image=images[ref.source]
        if not image then image=mod.assets:image(source.image);image:setFilter("nearest","nearest");images[ref.source]=image end
        local columns=source.columns or math.floor(image:getWidth()/16)
        local quad=love.graphics.newQuad(tile%columns*16,math.floor(tile/columns)*16,16,16,image:getDimensions())
        love.graphics.draw(image,quad,x,y)
      end
    end
    local function render(entry)
      love.graphics.push("all")
      for _,over in ipairs({false,true}) do
        love.graphics.setCanvas(over and entry.ts.overImage or entry.ts.image)
        love.graphics.clear(0,0,0,0);love.graphics.origin()
        for i,refs in ipairs(entry.slots) do
          local x,y=(i-1)%entry.ts.cols*16,math.floor((i-1)/entry.ts.cols)*16
          for _,ref in ipairs(refs) do drawRef(ref,x,y,over) end
        end
      end
      love.graphics.pop()
    end
    for id,source in pairs(layered.maps) do
      local map=assert(ctx.game.data.maps[id],"Missing map "..id)
      local slots,seen,cells,behaviors={},{},{},{}
      local width,height=source.cellWidth,source.cellHeight
      for index=1,width*height do
        local refs,key={},{}
        local behavior=0
        for _,layer in ipairs(source.layers or {}) do
          local ref=(layer.cells or {})[index]
          if layer.export~=false and ref then
            refs[#refs+1]={source=ref.source,tile=ref.tile,opacity=layer.opacity or 1}
            key[#key+1]=ref.source..":"..ref.tile..":"..(layer.opacity or 1)
            local pair=ref.source:match("^@runtime:(.+)$")
            if pair then behavior=(Interactions.behaviors[pair] or {})[ref.tile] or behavior end
          end
        end
        local mode=(source.collision or {})[index] or "solid"
        local painted={grass=2,water=16,door=105,cave=96,stairs=96,panel=103,
          ledge_down=56,ledge_up=57,ledge_left=58,ledge_right=59}
        behavior=painted[mode] or behavior
        key[#key+1]=mode;local signature=table.concat(key,"|")
        local mid=seen[signature]
        if mid==nil then mid=#slots;seen[signature]=mid;slots[#slots+1]=refs;behaviors[mid]=behavior end
        local coll=mode=="solid" and 255 or 0
        local original=(source.gen3Collision or {})[index]
        if original and ((original==0 and mode=="walk") or (original~=0 and mode=="solid")) then coll=original end
        cells[index]={mid=mid,coll=coll,elev=(source.gen3Elevation or {})[index] or 3}
      end
      local border=source.gen3Border or {width=1,height=1,mids={0}}
      local borderMids={}
      for i,mid in ipairs(border.mids) do
        borderMids[i]=#slots
        slots[#slots+1]={{source="@runtime:"..source.baseTileset,tile=mid,opacity=1}}
      end
      local cols=math.max(1,math.ceil(math.sqrt(#slots)))
      local rows=math.max(1,math.ceil(#slots/cols))
      local ts={cols=cols,rows=rows,midCount=#slots,midToSlot={},quads={},overQuads={},layered=true,
        image=love.graphics.newCanvas(cols*16,rows*16),overImage=love.graphics.newCanvas(cols*16,rows*16)}
      ts.image:setFilter("nearest","nearest");ts.overImage:setFilter("nearest","nearest")
      for i=0,#slots-1 do ts.midToSlot[i]=i end
      local pair="editor_"..mod.id.."_"..id
      local entry={ts=ts,slots=slots};render(entry);built[id]=entry
      T._pairs[pair]=ts;Interactions.behaviors[pair]=behaviors
      map.pair=pair;map.width=width;map.height=height
      map.midLayout=Layout.fromDecoded({width=width,height=height,cells=cells,
        borderWidth=border.width,borderHeight=border.height,borderMids=borderMids},id,pair)
    end
    if not View._editorLayerDispatch then
      View._editorLayerDispatch=true
      local draw=View.draw
      View.draw=function(...) return Runtime.call("editor.gen3.layers.draw",draw,...) end
    end
    local last=0
    mod.hooks:wrap("editor.gen3.layers.draw",function(proceed,game,...)
      local now=love.timer.getTime()
      if now-last>=1/30 then
        last=now
        local id=game and game.session and (game.session.mapId or game.session.map)
        if type(id)=="table" then id=id.id end
        local entry=built[id]
        if entry then render(entry);View._nativeDirty=true end
      end
      return proceed(game,...)
    end)
  end,-100)

end
